### ISSUE TITLE
[1장] 프레임워크, 라이브러리를 선택하는 기준

### ISSUE THREAD

**Issue by ghost** [FE-StudyWithMe/FE-without-framework#10]
## 🧐 Question
현업에서 개발하다가 새로운 라이브러리나 프레임워크를 도입해보면서 어떤 부분을 고려하게 되는지, 해당 툴을 도입하기까지 팀 내에서 어떤 부분에 대해서 논의했는지 궁금합니다!

## 📝 Reference
- [Vue.js 상태관리 라이브러리 도입기(Pinia와 VueX를 비교해봅시다!)](https://velog.io/@boyeon_jeong/Vue.js-%EC%83%81%ED%83%9C%EA%B4%80%EB%A6%AC-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EB%8F%84%EC%9E%85%EA%B8%B0Pinia%EC%99%80-VueX%EB%A5%BC-%EB%B9%84%EA%B5%90%ED%95%B4%EB%B4%85%EC%8B%9C%EB%8B%A4)
- [주니어의 Remix 도입기](https://velog.io/@yunsung_/%EC%A3%BC%EB%8B%88%EC%96%B4%EC%9D%98-Remix-%EB%8F%84%EC%9E%85%EA%B8%B0)

**Comment by kimfield98** [comment]
일한 기간이 짧아서 도입한 것을 본 적은 없지만, 최근 react -> next.js 움직임이 팀 내에 있었습니다.

<상황>
1. 기존에 팀원들이 잘 사용하던 라이브러리가 컴파일러 문제로 nextjs 최신 버전에서 사용할 수 없는 사례 발견 -> 고민중
2. 빠른 개발이 중요한 회사 특성을 고려하여 다른 팀원이 레퍼런스로 사용할 수 있는 프로젝트를 메인테이너가 따로 진행 중 -> 이후 확장 예정


저는 위 두 상황을 확인하면서
1. 기존에 사용하던 다른 툴과 충돌은 없는지
2. 팀 내에 많은 인원이 빠르게 습득하여 진행 속도에 문제가 없도록 할 수 있는지
등에 대해 논의하는게 중요하다고 생각했습니다!

**Comment by chhw130** [comment]
아무리 좋은 기술이라고 하더라도, 팀 상황에 맞게 선택해야 할 것 같습니다.

> 바쁘지 않은 상황이라면, 점진적으로 기술스택을 사용
But, 바쁜상황이라면, 팀원 모두가 쉽게 적용가능한 기술스택 사용
