### ISSUE TITLE
[2장] 과연 가상 DOM이 맞을까?

### ISSUE THREAD

**Issue by ghost** [FE-StudyWithMe/FE-without-framework#11]
## 🧐 Question
2장 > 동적 데이터 렌더링 섹션에서 가상 DOM이 아닌 실제 DOM 객체를 사용하여 diff 알고리즘을 구현한게 아닌가라는 생각이 드는데 다들 어떻게 생각하시는지 궁금합니다.

`applyDiff` 함수의 인자를 실제 DOM node인 `realNode`, 가상 DOM node인 `virtualNode`를 전달하는데 렌더링 전후로 비교한다면 두 node 모두 실제 DOM node여야 하지 않을까요?

```js
// 이 예제에서 realNode, virtualNode는 모두 DOM 객체 -> 이게 바로 Sevelte에서 추구하는 Real DOM인가?
// realNode, virtualNode 보다는 previousNode, nextNode 라는 이름이 더 낫지 않을까?
const applyDiff = (parentNode, realNode, virtualNode) => {
  if (realNode && !virtualNode) {
    realNode.remove();
    return;
  }

  if (!realNode && virtualNode) {
    parentNode.appendChild(virtualNode);
    return;
  }

  if (isNodeChanged(virtualNode, realNode)) {
    realNode.replaceWith(virtualNode);
    return;
  }

  const realChildren = Array.from(realNode.children);
  const virtualChildren = Array.from(virtualNode.children);

  const max = Math.max(realChildren.length, virtualChildren.length);

  for (let i = 0; i < max; i++) {
    applyDiff(realNode, realChildren[i], virtualChildren[i]);
  }
};
```

**Comment by kimfield98** [comment]
> **_렌더링 전후로 비교한다면 두 node 모두 실제 DOM node여야 하지 않을까요?_**
사실 이 문장에 대해서 잘 이해하지 못했지만 저의 의견은 다음과 같습니다.

위 코드 구현이 비교 알고리즘을 설명하고 있는 것 같고,
"비교"의 목적은 실제 DOM에 "효율적"이게 추가하거나 삭제하거나 교체하도록 하는 것이라고 생각해요.

예를 들어
```
if (!realNode && virtualNode) {
    parentNode.appendChild(virtualNode);
    return;
 }
```
이 코드에서 virtualNode는 아직 실제 DOM에 포함되지 않았지만, 
'포함될 수 있는 구조'의 '어딘가에 저장된' (ex. virtual DOM / 다른 메모리 공간) 어떠한 것이라고 생각해서
virtualNode라는 이름을 자연스럽게 받아들였던 것 같아요!

> 궁금한 점은 코드를 보고 어떻게 두 개 다 실제 DOM 요소라고 생각했는지? 가 궁금합니다 ㅎㅎ

**Comment by chhw130** [comment]
교제에서는 가상 dom(간단한 객체)로 비교하는게 아닌 실제 element를 비교하는 것 같습니다.
그러나 실제 element를 사용해서 비교하게 되면 너무 많은 속성을 비교해야 해서 비효율적인 것 같아요.
```
console.dir(document.body)
```
![스크린샷 2024-10-07 오전 10 00 33](https://github.com/user-attachments/assets/3f04c726-27b7-4967-8d94-8ddc4b75b9c0)

> 비교해야할 속성이 너무 많아짐...
