### ISSUE TITLE
[3장] 이벤트 핸들러 함수 네이밍 컨벤션이 어떻게 되나요??

### ISSUE THREAD

**Issue by chhw130** [FE-StudyWithMe/FE-without-framework#13]
## 🧐 Question
이벤트 핸들러 함수 네이밍을 어떻게 지으시나요??

저번 테오 세션에서 진행했던 컨벤션 만들기 기억하시나요?! 그 때 저희 팀같은 경우 이벤트관련 함수를 처리할 때 다음과 같이 합의했었습니다.
```javascript
on + {이벤트 행위} + {이벤트가 발생했을 때 트리거 되는 동작}
ex) 눌렀을때 로그인동작을 하는 이벤트 함수
const onClickLogin = () => {
 //로그인 동작
}
```

그런데 이벤트 함수에서 처리해야할 로직이 많아질 경우 함수이름이 길어질 수도 있다는 생각을 하게 되어 여러분들은 어떻게 네이밍 하시는 지 궁금합니다!

## 📝 Reference
예시) 이벤트 함수에서 `검증 -> 로그인(api) -> 리다이렉션` 등의 역할이 많아짐.

![image](https://github.com/user-attachments/assets/612762f9-1daa-4834-b9bd-0cd4b26c9ed5)

**Comment by horang-e** [comment]
이 부분 저희 조에서도 고민했었던 부분이였는데요! 그때 나왔던 얘기가 단순히 이벤트에 대한 반응만 한다면 on+이벤트 이런식으로 가겠지만 순수함수가 아닌 부수적인 함수도 처리하게 된다면 더 주가 되는 로직으로 handle+로직 이름을 짜자고 했던것 같습니다!
```js
onChangeId = (e) =>{
setId(e.target.value)
}

handleLogin = ()=>{
postLogin()
setId('')
}
```

**Comment by ghost** [comment]
제가 속한 개발팀에서는 `handleSaveButtonClick`, `handleInputChange` 처럼 `handle${이벤트 대상}${이벤트명}`으로 작성하고 있어요!

**Comment by kimfield98** [comment]
팀 내에 정한 규칙은 없기 때문에 개인적으로 판단해서 사용을 하는데
저는 on과 handle을 구분하는 것이 .. 구현 중에 제 뇌에 부하를 주는 것 같아 일단 handle로 통일해서 쓰는 중입니다 .. 하하
오늘 토론 때 의견 많이 듣고 제 코드에 적용해서 통일성있게 구현하고 싶네요 😭

**Comment by Joie-Kim** [comment]
제가 속한 프로젝트에서는 규칙을 딱 정한 건 아니지만,
`handle${이벤트명}${이벤트 대상}` 이런 식으로 이름을 지으려고 하고 있습니다. (정규님 팀이랑 순서만 다르네요..ㅎㅎ)
예시로 말씀 해주신 부분에 대해서는 `handleClickLogin()` 이렇게 함수 명을 짓고 그 안에서 비즈니스 로직과 관련된 함수들을 호출할 거 같아요.
근데 여기서 저도 고민이 되는 부분은 Login 자체가 동사 느낌이라, ClickLogin이라는 말이 뭔가 애매하게 느껴지더라구요.
이럴 때는 `handleLogin()`처럼 간결하게 쓰고 싶기도 하고..............😓

아무래도 회사에서는 Vue를 사용하고 있다보니까, `on`으로 시작하는 이름 보다는 `handle`로 시작하는 걸 더 많이 쓰는 거 같습니다.!

**Comment by kimfield98** [comment]
handleClickLoginButton -> 저는 이 버튼을 눌렀을 때 이런 일들을 수행할거야 라는 느낌으로 Button을 명시하는 편인데
handleLogin

가끔 너무 긴가 .. 싶긴 하더라구요
함수명을 읽을 때 제가 생각하는 방식처럼 다들 마음 속으로 어떻게 읽으시나요?(해석하시나요?) ㅎㅎ
