### ISSUE TITLE
[etc] 코드리뷰의 범위가 어디까지라고 생각하시나요??

### ISSUE THREAD

**Issue by chhw130** [FE-StudyWithMe/FE-without-framework#14]
## 🧐 Question
코드리뷰의 범위가 어디까지라고 생각하시나요??

저는 실무에서 코드 리뷰를 진행 중이기는 하지만 이해가 가지 않는 부분이 있습니다. 코드의 품질이나 컨벤션 등을 확인하기보다는 단순히 애플리케이션을 실행시켜서 기능이 잘동작되는지를 우선시하고 있습니다.

기능 동작 확인 하는 것도 중요하지만 코드 리뷰와는 다른 방향이고 `기능은 qa가 확인하면 되는 거 아니야?` 라는 생각이 있는데 어떻게들 생각하시나요!!

**Comment by horang-e** [comment]
물론 코드리뷰 자체가 구성원들끼리의 약속?이라 조직마다 다르겠지만 현우님 말에 완벽히 동의합니다! 기능작동 여부에 대한 내용은 코드리뷰 라기 보다는 qa에 가까운것같아요! 다만 PR에 모든걸 포함시키려다 보니 qa + 코드리뷰가 되지 않았나? 싶은 생각도 듭니다... 그나저나 코드 리뷰를 하는 회사라니 😲

**Comment by kimfield98** [comment]
저도 공감합니다. 기능이 잘 동작하는지 여부만이 코드리뷰의 주가 되면 아쉽다고 생각해요!

저는 사수님이 '불필요한 구현은 아닌지, 이해가 안되는 부분이 있다면 코드의 의도는 무엇인지' 등의 리뷰를 남겨주실 때
도움이 많이 되고 감사했던 기억이 있어요.
서로의 코드 스타일을 이해하기 위한 질문들을 좋아하는 것 같습니다 😆

**Comment by ghost** [comment]
저도 pr이 올라오면 로직을 더 간결하게 작성하는 방법이나 최적화 관련된 영역에 대해서 주로 피드백을 남기고 있어요!

실제 기능이 제대로 작동하는지 여부는 요건사항을 정확하게 알고 있는 담당 기획자가 확인하는게 더 부합하다고 생각합니다.
