### ISSUE TITLE
[3장] React에서 CustomEvent를 사용한다면?

### ISSUE THREAD

**Issue by ghost** [FE-StudyWithMe/FE-without-framework#16]
## 🧐 Question
저는 지금까지 React는 Vue와 다르게 사용자 정의 이벤트를 만들 수 없다는 걸로 알고 있었는데, 이번 장을 읽으면서 DOM API와 동일한 사용성을 가진 CustomEvent를 사용한다면 React에서도 충분히 구현할 수 있지 않을까라는 생각을 했습니다.

사용자 정의 이벤트를 사용한다면 컴포넌트 props로 콜백함수를 받아서 발생할 수 있는 리렌더링을 방지하기 위해 메모이제이션(`useCallback`, `useMemo`)을 적용할 필요가 없이 더 간결한 이벤트 핸들링 로직을 작성할 수 있을 것 같은데 다들 어떻게 생각하시나요?

## 📝 Reference

저와 비슷하게 생각하신 어떤 분이 [React에서 CustomEvent를 처리하는 패키지](https://github.com/HarshRohila/react-custom-events)를 만든 걸 찾아서 공유드립니다!

근데 제대로 관리되고 있는지는 모르겠네요😅

**Comment by kimfield98** [comment]
제가 CustomEvent라는 개념을 처음 접해서 잘 이해가 되지 않아
질문자의 의도대로 구현해달라고 Claude에게 부탁해서 받은 코드와 설명을 코멘트로 살포시 남겨봅니다 🤗

```js
import React, { useEffect, useRef } from 'react';

const CustomEventEmitter = ({ eventName, data, children }) => {
  useEffect(() => {
    const event = new CustomEvent(eventName, { detail: data });
    window.dispatchEvent(event);
  }, [eventName, data]);

  return children;
};

const CustomEventListener = ({ eventName, onEvent, children }) => {
  useEffect(() => {
    const handler = (event) => onEvent(event.detail);
    window.addEventListener(eventName, handler);
    return () => window.removeEventListener(eventName, handler);
  }, [eventName, onEvent]);

  return children;
};

const ChildComponent = () => {
  return (
    <CustomEventEmitter eventName="myCustomEvent" data={{ message: "Hello from Child!" }}>
      <div>Child Component</div>
    </CustomEventEmitter>
  );
};

const ParentComponent = () => {
  const handleCustomEvent = (data) => {
    console.log(data.message);
  };

  return (
    <CustomEventListener eventName="myCustomEvent" onEvent={handleCustomEvent}>
      <div>
        <h1>Parent Component</h1>
        <ChildComponent />
      </div>
    </CustomEventListener>
  );
};
```
이 예시에서는 CustomEventEmitter와 CustomEventListener 컴포넌트를 만들어 사용자 정의 이벤트를 발생시키고 처리합니다. 이렇게 하면 props로 콜백 함수를 전달하지 않아도 되므로, 메모이제이션을 사용할 필요가 없어집니다.
하지만 이 접근 방식에는 몇 가지 중요한 단점이 있습니다:

React의 단방향 데이터 흐름을 벗어납니다. 이는 애플리케이션의 예측 가능성과 디버깅을 어렵게 만들 수 있습니다.
전역 이벤트를 사용하므로, 큰 애플리케이션에서는 이벤트 충돌이나 의도치 않은 동작이 발생할 수 있습니다.
React의 가상 DOM 최적화와 충돌할 가능성이 있어, 성능 저하를 초래할 수 있습니다.
컴포넌트 간의 관계가 명시적이지 않아, 코드의 가독성과 유지보수성이 떨어질 수 있습니다.

결론적으로, 이 방식으로 구현은 가능하지만 React의 철학과 최적화 전략에 부합하지 않습니다. 대부분의 경우 React의 기본 패턴인 props와 상태 관리를 통한 방식이 더 안전하고 효율적입니다. 필요하다면 Context API나 외부 상태 관리 라이브러리를 사용하는 것이 더 나은 선택일 수 있습니다.

**Comment by ghost** [comment]
"React의 철학"이란 단어를 한 글자씩 읽으니까 뭔가 1장에서 언급된 "기묘함"이 느껴지면서 "React도 프레임워크라고 볼 수 있을 것 같은데?"라는 생각이 드네요🤣

**Comment by kimfield98** [comment]
우리 강경 라이브러리파 이렇게 해체되는 건가요 🤪
