### ISSUE TITLE
[3장] 속성에 이벤트 핸들러를 등록하는 방식이 꼭 안티 패턴일까요?

### ISSUE THREAD

**Issue by ghost** [FE-StudyWithMe/FE-without-framework#17]
## 🧐 Question
책에서 DOM node의 `on-` prefix를 가지는 속성으로 이벤트 핸들러를 등록하는 방식은 이전에 등록된 핸들러를 덮어쓸 수 있으니 사용을 지양해야 한다고 말하고 있는데, 개인적으로 동일한 이벤트에 대해 핸들러를 여러 번 등록하는 경우가 과연 흔할까라는 생각이 들었어요.

단일 node에 핸들러를 여러 번 등록하는 것보다는 핸들러 내부 로직에서 분기처리를 하거나 기능 단위로 단일 핸들러를 가지는 node들을  조건부로 노출시키는 방법이 낫지 않을까요?

그리고 한번 등록한 핸들러를 메모리로부터 제거하는 부분은 오히려 속성으로 지정하는 방식으로 구현하는게 핸들러에 대한 참조가 유지되어야 하는 이벤트 리스너 방식보다 더 간단하지 않을까라는 생각도 들었는데 다들 어떻게 생각하시나요?

```js
buttonNode.onclick = (event) => { ... };

// 적절한 시점에
buttonNode.onclick = null;
```

**Comment by kimfield98** [comment]
라이브러리나 프레임워크를 주로 사용하다보니 저수준 DOM API를 어떻게 조작하는게 효율적일지 전혀 생각해본 적이 없는데,
책을 읽고 이런 질문을 생각해내시다니 .. 대단한데요 🤭

1. on- 접두사 사용 (권장되지 않는 방식):
```js
// HTML: <button id="myButton">Click me</button>

const button = document.getElementById('myButton');

// 첫 번째 핸들러 등록
button.onclick = function() {
    console.log('First handler');
};

// 두 번째 핸들러 등록 (첫 번째 핸들러를 덮어씁니다)
button.onclick = function() {
    console.log('Second handler');
};

// 결과: 버튼 클릭 시 'Second handler'만 출력됩니다.
```

> 질문) 책에서 DOM node의 on- prefix를 가지는 속성으로 이벤트 핸들러를 등록하는 방식은 이전에 등록된 핸들러를 덮어쓸 수 있으니 사용을 지양해야 한다고 말하고 있는데, 개인적으로 동일한 이벤트에 대해 핸들러를 여러 번 등록하는 경우가 과연 흔할까라는 생각이 들었어요.

> 답변) 제 생각에 요구사항이 늘어나고 여러 명이 코드를 관리할 경우 이벤트를 위 코드처럼 덮어쓸 수 있으니
차라리 아래 코드처럼 추가해라!를 권장하는 게 아닌가 .. 생각했어요 ㅎㅎ

2. addEventListener 사용 (권장되는 방식):
```js
// HTML: <button id="myButton">Click me</button>

const button = document.getElementById('myButton');

// 첫 번째 핸들러 등록
button.addEventListener('click', function() {
    console.log('First handler');
});

// 두 번째 핸들러 등록
button.addEventListener('click', function() {
    console.log('Second handler');
});

// 결과: 버튼 클릭 시 'First handler'와 'Second handler' 모두 출력됩니다.
```

> 질문) 단일 node에 핸들러를 여러 번 등록하는 것보다는 핸들러 내부 로직에서 분기처리를 하거나 기능 단위로 단일 핸들러를 가지는 node들을 조건부로 노출시키는 방법이 낫지 않을까요?

> 답변) 이 부분에 대해서는 공감해요! 로직을 코드로 드러내는 것이 이벤트를 관리하기 더 수월할 것이라고 생각합니다

> 질문) 그리고 한번 등록한 핸들러를 메모리로부터 제거하는 부분은 오히려 속성으로 지정하는 방식으로 구현하는게 핸들러에 대한 참조가 유지되어야 하는 이벤트 리스너 방식보다 더 간단하지 않을까라는 생각도 들었는데 다들 어떻게 생각하시나요?

> 답변) buttonNode.onclick = null; 이 방식은 간단한 만큼 모든 핸들러가 제거되기 때문에 특정 핸들러만 선택적으로 제거하고 싶은 상황에서는 button.removeEventListener('click', handler1); 이런식으로 사용하는 것이 좋을 것 같아요!

3. React에서의 이벤트 처리 (현대적인 프레임워크 방식):
```js
import React from 'react';

function MyButton() {
    const handleClick1 = () => {
        console.log('First handler');
    };

    const handleClick2 = () => {
        console.log('Second handler');
    };

    return (
        <button onClick={() => {
            handleClick1();
            handleClick2();
        }}>
            Click me
        </button>
    );
}

// 결과: 버튼 클릭 시 'First handler'와 'Second handler' 모두 출력됩니다.
```

**Comment by chhw130** [comment]
메모리 누수 관련해서 문제가 생길 수 있어요.

```javascript
let someVar = 'data';
buttonNode.onclick = (event) => {
  console.log(someVar); // 외부 변수를 참조
};
buttonNode.onclick = null;
```
이벤트함수는 에서 외부 변수를 참조하지만, 이벤트함수의 생명주기가 끝나도 외부 스코프의 변수를 참조하고 있기 때문이에요.

## 해결 

```javascript
let someVar = 'data';
const handleClick = (event) => {
  console.log(someVar); // 외부 변수를 참조
};

buttonNode.addEventListener('click', handleClick);

// 이벤트 리스너 해제
buttonNode.removeEventListener('click', handleClick);
```
그래서 이벤트 리스너를 등록하고 `removeEventListner`를 통해 이벤트 리스너를 해제하면 외부 변수에 대한 참조가 사라지고 가비지 콜렉터에 의해 메모리가 지워집니다!

**Comment by ghost** [comment]
> 이벤트함수는 에서 외부 변수를 참조하지만, 이벤트함수의 생명주기가 끝나도 외부 스코프의 변수를 참조하고 있기 때문이에요.(클로져)

`buttonNode.onclick`에 null을 대입하면 이전에 할당했던 함수에 대한 참조가 없어지니까 가비지 컬렉터에 의해서 회수되지 않나요??

**Comment by chhw130** [comment]
@jasongoose 
함수에 대한 참조는 사라지지만, 함수 내부 스코프에서 외부 변수를 참조하고 있는 건 메모리에 사라지지 않을 수도 있어요!

약간 다른 느낌이기는 한데 weakMap, weakSet이 만들어진 이유도 이때문이에요. (도달 가능할 수도 있는 참조 값은 메모리에서 사라지지 않음.)
https://ko.javascript.info/weakmap-weakset

**Comment by ghost** [comment]
> 함수에 대한 참조는 사라지지만, 함수 내부 스코프에서 외부 변수를 참조하고 있는 건 메모리에 사라지지 않을 수도 있어요!

핸들러 내에서 외부변수인 `someVar`를 참조하는 건 실제 `click` 이벤트가 발생하여 핸들러가 실행될 때 일어나니까 핸들러가 모두 실행되고 나서는 내부 스코프가 없어지면서 `someVar`에 대한 참조도 같이 사라지지 않을까요??

그리고 클로져는 종료되어야 하는 상위 스코프가 하위 스코프에 의해서 유지되는 현상인데, 인용된 위 문장은 하위 스코프에서 상위 스코프를 참조하니까 하위 스코프가 유지된다는 방향으로 설명한 것 같아서 차이가 있다고 생각합니다!

**Comment by chhw130** [comment]
@jasongoose  제가 알고 있던 부분이 틀릴 수도 있어서, gpt랑 claude로 더블 체크 해봤습니다! 
물론 AI가 항상 정확한 답변을 내놓는 것은 아니라고 생각해서 한번 체크하고 얘기해 보면 좋을 것 같네요!

<img width="466" alt="스크린샷 2024-10-13 오후 7 26 28" src="https://github.com/user-attachments/assets/e24affe4-f821-4970-9026-2860fefed9ae">

<img width="368" alt="스크린샷 2024-10-13 오후 7 27 14" src="https://github.com/user-attachments/assets/bb0b2a9c-9f31-4aa9-bfdb-42680410cba2">
