### ISSUE TITLE
[3장] 이벤트 처리 관련 문제 해결 경험이 있나요!?

### ISSUE THREAD

**Issue by Joie-Kim** [FE-StudyWithMe/FE-without-framework#19]
## 🧐 Question
- 작년 즈음.. 기능 QA를 하던 중 '간헐적으로 목록에 있는 요소가 클릭이 안 된다'는 이슈가 배정되어 확인해보니, button 태그 안에 있던 span 태그들이 눌려 button에 바인딩 된 handleClick 이벤트가 제대로 동작하지 않은 것이 원인이었는데요.
- 이 문제를 해결하기 위해 script 로직으로 고군분투 하던 중, 같이 프로젝트를 하던 사수님이 css 속성으로 아주 간단하게 1초만에 해결을 해주신 게 생각이 나네요..
>- button 내부에 있던 요소들에게 `pointer-events: none;`을 줘서 해결했답니다... 🫣
```vue
<ul v-if="playList?.length" class="content">
  <li
    v-for="(item, i) in playList"
    :key="`preview-${item.contentSeq}-${i}`"
    class="content__item"
    :class="i === selectedIndex ? 'content__item--selected' : ''"
    :data-index="i"
    draggable="true"
    @dragstart="handleDragStart($event)"
    @dragenter="handleDragEnter($event)"
    @dragover="handleDragOver($event)"
    @dragleave="handleDragLeave($event)"
    @drop="handleDrop($event)"
  >
    <button class="content__item__box" @click="handleClick(i)">
      <span class="content__item__no">{{ i + 1 }}</span>
      <span class="content__item__title">{{ item.title }}</span>
      <span class="content__item__icon">
        <i class="fa-solid fa-bars"></i>
      </span>
    </button>
    <div class="content__item__expose">
      <GzSelect v-model="item.time">
        <option v-for="option in exposeOptions" :key="option.value" :value="option.value">
          {{ option.name }}
        </option>
      </GzSelect>
    </div>
  </li>
</ul>
```

- 여러분들은 업무 혹은 프로젝트를 하던 중, 이벤트를 처리하는 데에 이슈를 겪은 경험이 있나요!? 있다면 공유해주세요! :D

**Comment by chhw130** [comment]
@Joie-Kim  저도 똑같은 경험을 한 적이 있었습니다.
특정 버튼 내부에 svg icon을 넣고 button에 이벤트 처리를 했는데, svg관련 태그들이 눌리는 문제가 있더라고요.
svg가 실제로는 엄청 복잡하게 백터형식으로 구성되어 있어서 그런거 같습니다.
```html
<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg">
  <g fill="none" stroke="black" stroke-width="3">
    <circle cx="50" cy="50" r="40" />
    <path d="M 20 80 Q 50 20 80 80" />
  </g>
</svg>
```

그래서 저도 희주님이랑 똑같이 `pointer-events: none;`속성으로 해결했던 기억이 났습니다. ㅋㅋㅋ

**Comment by ghost** [comment]
저는 개발하다가 이벤트 버블링으로 인해서 하위 node 이벤트 핸들러 뿐만 아니라 상위 node의 이벤트 핸들러까지 실행되는 버그가 있어서 vue에서 제공하는 [event modifier 중 하나인 `.stop`](https://vuejs.org/guide/essentials/event-handling.html#event-modifiers)를 적용했던 경험이 있어요!

**Comment by kimfield98** [comment]
https://github.com/FE-StudyWithMe/FE-without-framework/issues/12

서현 님 이슈 댓글에 남긴 해결 경험이 있습니다!
