### ISSUE TITLE
[1장] 그래서 결국 React는 프레임워크인 것일까?

### ISSUE THREAD

**Issue by horang-e** [FE-StudyWithMe/FE-without-framework#2]
## 🧐 Question
그래서 결국 React는 프레임워크인 것일까?

## 💡Description
책에서는 "기묘함"을 이유로 react를 프레임 워크라고 칭했는데요! 책에서 기술한 제약 조건 언어,의존성 주입, 옵저버블 을 보면 100% 리액트가 프레임 워크인가? 라는 생각을 계속 하면서 책을 읽었던것 같아요. React는 분명히 많은 사람들이 쓰는대로 쓰지 않으면 뭔가 "기묘" 하지만 그래도 그렇게 되도 원하는 결과대로 돌아가는걸? 하는 생각을 무의식중에 했었습니다. 그래서 저는 React는 라이브러리라고 생각해요! 여러분들의 의견은 어떠신가요?

![스크린샷 2024-10-04 오후 9 25 23](https://github.com/user-attachments/assets/ec0b8af3-aa78-4719-abff-34b092f46a59)

## 📝 Reference
[리액트 19 컴파일러 추가](https://okky.kr/articles/1498070?topic=community&page=1)
약간 토론같은 글을 찾다가 흥미로워서 공유해봅니다.

**Comment by ghost** [comment]
전 React가 추구하는 선언적 패러다임과 상태를 업데이트하여 DOM을 조작하는 부분은 라이브러리로서 제공하는 기능의 일부라고 생각해요.

그리고 프레임워크는 프로젝트 단위의 스캐폴드를 제공한다는 점에서 라이브러리와 큰 차이점이 있는데 React를 사용하기 위해서 꼭 갖춰야 하는 폴더 구조는 없으니 라이브러리가 아닐까요?

**Comment by kimfield98** [comment]
저는 React를 라이브러리라고 생각하며 사용하고 있어요.

프레임워크로 분류되는 Django, Next.js는 꼭 지켜야하는 규칙(예를 들어 폴더 구조나 파일명 등)이 있어 
초반에 이것만 학습하고 익숙해지면 내가 개발을 좀 하는구나.. 싶었던 것 같은데,  😂
같은 것을 리액트로 다시 만드려고 하니 라우팅부터 자유도가 확! 높아져 스스로 결정해야 할 부분이 많더라구요. 

정규님 의견과 비슷한 것 같은데, 꼭 지켜야 하는 규칙이 없으니 리액트는 라이브러리라고 볼수있지 않을까요? 😄
