### ISSUE TITLE
[etc] 여러분들은 이 책을 읽으면서 무슨 생각을 하시나요?

### ISSUE THREAD

**Issue by horang-e** [FE-StudyWithMe/FE-without-framework#22]
## 🧐 Question

이건 계속 머릿속에 있던 질문이였는데 이제 딱 책의 절반을 읽은 시점에서 여쭤보는게 좋을것같아서 질문드려요!
여러분들은 이 책을 읽으면서 무슨 생각을 하시나요?
저는
 **"오! 프레임 워크는 이런거고 프레임 워크가 이런식으로 돌아가는거 였구나?! 😮 그럼 리액트에서는 이걸 어떻게 적용시킨거지?"**
이런 생각을 하면서 클로드랑 긴밀하게 대화해요.. 클로드야 그럼 이건 이게맞아? 리액트에서는 어떻게 적용된거야? 이러면서 공부중입니다.

근데 책 이름 자체가 프레임워크 없는 프론트엔드 개발 이다 보니까 이걸 읽으면서 "음.. 프레임워크 없이 개발 해봐야겠군!" 이라는 멋진 생각을 하시는지 궁금합니다. 👉👈 그리고 어떻게 공부하시는지도 궁금해요!(너무 제 스스로가 ai 의존도가 올라간것 같은 기분이 들어서..)

+ 읽으면서 이게 한국어가 맞아? 뭔소리야? 라고 항상 생각하기도 합니도..번역 똥망💩

**Comment by chhw130** [comment]
@horang-e 
저는 프레임워크에서 해주는 기능들이 추상화되어있었기 때문에 깊게 생각해보지 못한 부분들이 있었어요.

> 가령 제가 처음 개발을 접했을 때 리액트에서 해주는 상태관리는 클로져로 되어 있으니 '다른 라이브러리도 클로져를 기반으로 상태관리를 해주는 걸거야!' 라는 함정에 빠졌었습니다. 사실 상태관리라는게 proxy, observer, rxjs 등으로도 충분히 구현될 수 있는데 말이죠.

즉, 자주 사용되는 프레임워크의 논리에만 사로잡혀있어 넓은 시야로 바라 보지 못했던 것 같아요. 이번 챕터에서도 custom-element를 이용해 컴포넌트를 구축할 수 있고, 실제로 이를 이용한 프레임워크가 있다는 것도 신기했어요. ㅋㅋㅋ

**Comment by kimfield98** [comment]
저는 사실 책의 내용에 집중하기보다는 이슈를 통해 저희가 나누는 대화에 집중하는 방향으로 스터디에 참여하고 있었어요 😅

하지만 이번 장의 담당으로 Web Component에 대해 이해하려고 최선을 다해보니
해당 개념이 왜 등장했는지, 현재의 어떠한 문제를 해결할 수 있는지 알게 되었고 자연스레 이후에도 어떻게 적용할 수 있을지 고민하게 되더라고요!

이렇게 강제로 책임감을 부여받지 않았다면(?)
아마 토론만 즐기며 현재 사용하고 있는 라이브러리나 프레임워크 단에서만 고민하고 내용을 공유하고 발전이 없었을 것 같아요.
더 집중해야겠지만 이것만으로도 큰 걸음을 떼었다고 생각하고 앞으로 더 톺아볼 다짐을 했답니다 😁

**Comment by Joie-Kim** [comment]
지금까지는 '오 브라우저에 이런 기능도 있었군' 하면서 읽었던 거 같습니다.
책에 있는 코드를 따라 안 해보고 이해만 하고 넘어갔어요. 그래도 책의 내용을 습득하는 데에 문제가 없었거든요..

근데 이번 3장의 내용을 보면서 '예제 코드를 따라 직접 만들어봐야겠는데..?'하고 생각하게 됐습니다.
직접 써보는 게 더 중요한 내용들 같다고 느껴졌거든요. 🤔

다음 장에서 또 마음이 바뀔 수도 있겠지만, 이번 장은 한 번 코드를 직접 작성하고 브라우저에서 실행해보려고 해요!

**Comment by ghost** [comment]
> 여러분들은 이 책을 읽으면서 무슨 생각을 하시나요?

지금까지 프레임워크, 라이브러리로만 개발하다가 실제 DOM API로 동적으로 렌더링하는 방법을 공부해보니 개인적으로 꽤 신세계였어요😄
"이 정도면 그냥 웹 컴포넌트로 개발해도 되겠는데?" 라는 생각도 들었고 한번 웹 컴포넌트로 간단한 사이드 프로젝트를 해보고 싶은 욕심도 생겼던 것 같아요!

> 그리고 어떻게 공부하시는지도 궁금해요!

내용을 정리하면서 책을 읽다가 중간에 코드가 나오면 클론받은 프로젝트 열어서 소스도 보고 실제로 실행해서 확인해보고 있습니다.
뭔가 이해가 안되면 검색해보고 gpt한테 물어보기도 해요!

> 읽으면서 이게 한국어가 맞아? 뭔소리야? 라고 항상 생각하기도 합니도..번역 똥망💩

저도 아래 내용을 이해하는데 조금 시간이 걸렸던 것 같아요ㅠ
![Screenshot 2024-10-19 at 5 12 05 PM](https://github.com/user-attachments/assets/357edc74-fbfe-43c1-a448-da9f5283709d)

**Comment by 2min0-dev** [comment]
저는 '책에 나온 개념이 기존에 사용하고 있던 프레임워크(또는 라이브러리)에서 어느 부분과 유사한가'를 가장 많이 생각하는 것 같아요.
그러다보니 자연스럽게 질문에도 항상 그러한 내용을 작성하고 있기도 해요 ㅎㅎ
질문을 작성하다 보면 관련된 내용에 대한 개념을 찾아보게 되는데, 정확한 개념을 모르고 무의식 중에 사용하던 것들에 대한 자세한 내용을 알 수 있게 되어 좋았어요.

그 외에도 다양한 관점과 의견을 들으며 새로운 내용들을 많이 얻어가는 시간으로 스터디를 활용 중 입니다:)
