### ISSUE TITLE
[4장] 섀도우 DOM에 대해 더 생각해보기

### ISSUE THREAD

**Issue by Joie-Kim** [FE-StudyWithMe/FE-without-framework#24]
### 1. SEO 측면에서 섀도우 DOM의 장단점
- 검색 엔진 크롤러가 섀도우 DOM 내부의 콘텐츠를 제대로 인식할 수 있을까요..?
- 섀도우 DOM을 사용하는 경우 SEO가 저하될 가능성은 없는지 그리고 만약 저하된다면 어떻게 극복할 수 있을까요?
### 2. 접근성과 성능 최적화
- 섀도우 DOM을 사용할 때 접근성(Accessibility)에 미치는 영향은 없을까요..?
- 그리고 성능 최적화가 왜 되는 건지 와닿지 않았습니다..
>- [책에 있는 참고 아티클](https://develoger.com/shadow-dom-virtual-dom-889bf78ce701)을 읽어보았지만.. 
### 3. 프레임워크 환경에서의 충돌 가능성
- 프레임워크 환경(React, Vue...와 같은)에서 섀도우 DOM을 사용했을 때 충돌이 일어날 가능성은 없을까요?

## 📝 Reference
- 이슈 먼저 올려뒀어요. 저도 찾아보고 댓글 남기겠습니다! :D

**Comment by horang-e** [comment]
오 덕분에 뒤에 언급이 없어서 공부하지 않았던 섀도우DOM 에 대해 한번더 찾아보고 공부하는 계기가 되었습니다!!! bbbb

> SEO 측면에서 섀도우 DOM의 장단점

 구글의 검색 엔진에서는 섀도우 DOM을 평면화 해서 읽어 온다고 합니다! 
```js
<script>
  class MyComponent extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: 'open' });
    }

    connectedCallback() {
      let p = document.createElement('p');
      p.innerHTML = 'Hello World, this is shadow DOM content. Here comes the light DOM: <slot></slot>';
      this.shadowRoot.appendChild(p);
    }
  }

  window.customElements.define('my-component', MyComponent);
</script>

<my-component>
  <p>This is light DOM content. It's projected into the shadow DOM.</p>
  <p>WRS renders this content as well as the shadow DOM content.</p>
</my-component>
            
```
위처럼 만들면 랜더링 후 구글은
```js
<my-component>
  Hello World, this is shadow DOM content. Here comes the light DOM:
  <p>This is light DOM content. It's projected into the shadow DOM<p>
  <p>WRS renders this content as well as the shadow DOM content.</p>
</my-component>
```
이렇게 읽어 온다고 합니다! 그렇기 때문에 mode : 'open'을 사용해서 만든다고 한다면 SEO저하는 없을 것이라고 생각됩니다! 
'closed'모드에 대해서는 web.dev에서 
<img width="546" alt="스크린샷 2024-10-19 오후 11 51 36" src="https://github.com/user-attachments/assets/682cd6f4-6aaf-4dcb-8c3b-cf93f81e6818">
라고 나왔고 
`Note: Closed shadow roots are not very useful. Some developers will see closed mode as an artificial security feature. But let's be clear, it's not a security feature. Closed mode simply prevents outside JS from drilling into an element's internal DOM.`
라고도 언급 된걸 보니 open 과 매한가지로 읽어오지 않을까..요?



[섀도우 돔에 대한 블로그](https://guiyomi.tistory.com/157)
[SEO와 섀도우 돔에 대한 테스팅](https://dev.to/stuffbreaker/seo-and-web-components-2023-edition-3l6i)
[구글의 서치콘솔이 Shadow DOM을 처리하는 방법](https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics?hl=ko#web-components)
[closed 모드는 왠만하면 쓰지말아라!](https://web.dev/articles/shadowdom-v1?hl=ko#terminology_light_dom_vs_shadow_dom)

**Comment by Joie-Kim** [comment]
@horang-e  갓서현 ....... 관련해서 리서치 하러 들어왔다가 감동하고 갑니다 ...... 🥹

**Comment by Joie-Kim** [comment]
- [섀도우 돔 mdn 문서](https://developer.mozilla.org/ko/docs/Web/API/Web_components/Using_shadow_DOM)
- [어려운 블로그 글.. (aka. 번역체는 힘들어)](https://nolanlawson.com/2022/11/28/shadow-dom-and-accessibility-the-trouble-with-aria/)
>- 섀도우 DOM에서 ARIA 속성을 사용할 때의 문제를 다루고 있다. 특히 aria-labelledby와 같은 속성이 전역 ID 참조에 의존하는데, 섀도우 DOM 내부에서는 ID가 로컬로 스코프되기 때문에 다른 섀도우 루트나 전역 DOM의 요소를 참조할 수 없다. 이로 인해 ARIA 속성 사용에 어려움이 생길 수 있고, 현재 이를 해결하기 위한 기술적 노력(AOM, ARIA 리플렉션 등)이 진행 중이지만, 브라우저 지원은 아직 제한적이다.
- [쉬운 블로그 글](https://nuli.navercorp.com/community/article/1133158)
- GPT의 답변..
>- 섀도우 DOM을 프레임워크 환경(React, Vue 등)에서 사용할 때 몇 가지 충돌 가능성이 있어.
>- Virtual DOM과의 충돌: React와 같은 프레임워크는 Virtual DOM을 사용해 효율적으로 UI 업데이트를 처리하는데, 섀도우 DOM은 브라우저의 실제 DOM을 독립적으로 관리해. 이로 인해 React의 Virtual DOM이 섀도우 DOM 내에서 발생한 변화를 감지하지 못할 수 있어.
>- 스타일 및 이벤트 관리: 섀도우 DOM의 스타일 캡슐화가 프레임워크의 스타일 시스템과 충돌할 수 있고, 이벤트 버블링도 섀도우 DOM과 프레임워크 간에 다르게 동작할 가능성이 있어.
>- 이러한 문제를 해결하려면 섀도우 DOM을 적절히 관리하는 추가적인 코드나 설정이 필요할 수 있어.

**Comment by chhw130** [comment]
오오 shadow dom을 책에서는 자세히 다루지 않아, 그냥 가볍게 읽고 넘겼는데 찾아보니 흥미로운게 많네요.

저는 `shadow dom을 사용하면 왜 성능적으로 좋을까??` 라는 물음 위주로 서칭 해보았는데요.
- 섀도우 DOM은 메인 문서 DOM과 별도의 렌더링 트리를 형성한다.
- 브라우저는 섀도우 DOM 내부의 변경사항을 독립적으로 처리한다.

-> 결과적으로 독립적인 DOM으로 동작하다 보니 reflow, 리렌더링, dom 파싱 등 연산이 많이 드는 작업들도 shadow dom 스코프 안에서만 동작해서 더 효율적이라는 것 같아요.

추가로 video태그도 shadow DOM을 기반으로 동작한다고 하네요.

**Comment by Joie-Kim** [comment]
### Q. 프레임워크 환경에서 섀도우 DOM을 잘 사용하기 위해 어떤 설정을 해줘야 해?

섀도우 DOM과 프레임워크(React, Vue 등)를 함께 사용할 때 추가적인 코드나 설정이 필요한 예시를 몇 가지 설명할게.

- React에서 dangerouslySetInnerHTML 사용: 섀도우 DOM에 접근하고 직접 HTML을 삽입하려면 React에서는 dangerouslySetInnerHTML을 사용해 섀도우 DOM의 콘텐츠를 처리할 수 있어. 이는 React의 Virtual DOM이 해당 부분을 무시하도록 하기 때문에 필요해.

- 이벤트 버블링 관리: 섀도우 DOM 안에서 발생한 이벤트가 부모 컴포넌트로 전달되지 않도록 설정해야 해. React와 Vue에서 customEvent나 이벤트 위임을 사용해 이벤트를 관리할 수 있어.

- 스타일 호환성: 섀도우 DOM은 캡슐화된 스타일을 적용하므로 프레임워크에서 사용하는 전역 스타일이나 CSS-in-JS 방식은 제대로 적용되지 않을 수 있어. 이 경우 스타일을 컴포넌트 안에 직접 정의하거나 ::part와 같은 방법을 사용해 스타일을 외부에서 제어할 수 있어.

이런 방식으로 섀도우 DOM과 프레임워크 간 충돌을 완화할 수 있어.

### Ref
- [dangerouslySetInnerHTML](https://velog.io/@ferrari_roma/%EB%A6%AC%EC%95%A1%ED%8A%B8%EC%97%90%EC%84%9C-dangerouslySetInnerHTML-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
- [DOM 엘리먼트 (리액트 옛날 문서..)](https://ko.legacy.reactjs.org/docs/dom-elements.html)

**Comment by horang-e** [comment]
<img width="855" alt="스크린샷 2024-10-20 오후 10 02 47" src="https://github.com/user-attachments/assets/de513c47-76b2-489f-9577-cf9dfeee12f6">
