### ISSUE TITLE
[4장] 책의 예제 코드에 대해서

### ISSUE THREAD

**Issue by chhw130** [FE-StudyWithMe/FE-without-framework#26]
## 🧐 Question
113페이지 예제 질문입니다!

```javascript
attributeChangedCallback(name, oldValue, newValue){
    if(!this.hasChildNodes()){
        return
    }
}
```
속성이 바뀔때 diffing알고리즘을 수행하는 부분에서 왜 자식노드가 없다면 return해줄까요?? 현재 element는 diffing알고리즘을 수행시켜줘야 하는거 아닌가요?? 제가 놓치고 있는 부분이 있는지 궁금합니다!

**Comment by ghost** [comment]
> 속성이 바뀔때 diffing알고리즘을 수행하는 부분에서 왜 자식노드가 없다면 return해줄까요??

저는 실제 화면에 표시되는 DOM node가 `HelloWorld` 컴포넌트가 아니라 자식 요소인 `<div></div>`이기 때문에 비교할 대상이 없는 경우(`this.hasChildNodes() ===  false`)에는 diff를 수행하지 않는 걸로 이해했습니다!

![Screenshot 2024-10-19 at 11 46 55 PM](https://github.com/user-attachments/assets/f77a36ff-2f72-4e6f-b990-e2c3c858b10f)
