### ISSUE TITLE
[4장] 이 내용은 어떻게 이해하셨나요?

### ISSUE THREAD

**Issue by ghost** [FE-StudyWithMe/FE-without-framework#27]
## 🧐 Question
[서현님 pr 코멘트](https://github.com/FE-StudyWithMe/FE-without-framework/pull/23#discussion_r1807331321)를 한번 이슈로 가져와 보았습니다!

아래 책 109 페이지의 내용이 헷갈리는데 혹시 다들 어떻게 이해하셨나요??

![Screenshot 2024-10-19 at 5 12 05 PM](https://github.com/user-attachments/assets/a22a9ffd-0aaa-4616-8abb-69b85b40c900)

**Comment by ghost** [comment]
> 문자열 값을 가지지 않는 속성에 대해서는 필요한 경우에 한해서 getter를 구현하고 setter만 구현해도 충분하다.

저는 우선 위와 같이 이해했습니다;

**Comment by horang-e** [comment]
> 그럼에도 불구하고 이 방법에는 한가지 단점이 있다. HTML 속성은 문자열이다. 따라서 문자열이 아닌 속성이 필요한 경우 먼저 속성을 변환해야한다. 

이 부분 같은 경우는 
```js
<div id="myDiv" data-count="5" data-active="true"></div>
```
이렇게 있을 때 `id`, `data-count`, `data-active` 는 모두 문자열 속성 값을 가집니다. 
이 때, `data-count` : number, `data-active`: boolean 타입으로 값을 사용하고 싶다면 `parseInt()`와 비교 연산자 등을 통해 속성 값을 가져와야 원하는 타입으로 사용 가능하다는 뜻으로 이해했고

그 아래는 저도 이해하지 못했어요... :(

**Comment by Joie-Kim** [comment]
서현님 PR에 [민영님이 남겨주신 댓글](https://github.com/FE-StudyWithMe/FE-without-framework/pull/23#discussion_r1807362166) 보고 이해 완료 했습니다..! 🤓
이슈 보기 전에 PR부터 봤거든요..헿
