### ISSUE TITLE
[5장] 백엔드분들과 협업할 때 어떻게 하시나요??

### ISSUE THREAD

**Issue by chhw130** [FE-StudyWithMe/FE-without-framework#30]
## 🧐 Question
여러분들은 백엔드분들과 협업할 때 어떻게 하시나요??

입사 초반까지 저는 백엔드에서 api response interface를 어떤 형식으로 주던 프론트에서 처리 할 수 있다! 라는 생각이였습니다.(자신감 넘쳤던 시절..)
그러다 생각이 바뀌었는데요. 이유는 다음과 같았습니다.

- 프론트측에서 필요한 값보다 더 많은 응답 인페이스가 주어져 성능 문제로 이어질 수 있음.
```javascript
// Backend types
interface ProductEntity {
  id: number;
  name: string;
  price: number;
  stock: number;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  categoryId: number;
  description: string;
  metadata: object;
  // ... 더 많은 내부 필드들
}

// Frontend에서 실제로 필요한 인터페이스
interface ProductListDTO {
  id: number;
  name: string;
  price: number;
  stock: number;
}
```
- api에서 받은 데이터를 그대로 사용할 수 없어, 프론트측에서 추가적인 연산이 필요함.
```javascript
// 비효율적인 예시
// 백엔드 응답
{
  "orders": [
    { "id": 1, "price": 1000, "quantity": 2 },
    { "id": 2, "price": 2000, "quantity": 1 },
    { "id": 3, "price": 3000, "quantity": 3 }
  ]
}

// 프론트엔드에서의 추가 연산
const orders = response.orders;
const totalAmount = orders.reduce((sum, order) => {
  return sum + (order.price * order.quantity);
}, 0);
const averagePrice = orders.reduce((sum, order) => {
  return sum + order.price;
}, 0) / orders.length;
```

그래서 백엔드에서 만들어주는 api를 그대로 작업하기보다는 api스펙에 대해 논의를 먼저 하는게 좋을 거 같다는 생각을 했습니다.
백엔드분들과 작업할 때 여러분들은 어떻게 하시나요?? 혹은 다른 이슈들이 있으셨나요??
BFF를 구성해보신 경험은 있으실까요??

## 📝 Reference
[graphql과 bff](https://f-lab.kr/insight/graphql-bff-pattern-microservices-20240628)
[BFF](https://fe-developers.kakaoent.com/2022/220310-kakaopage-bff/)

**Comment by horang-e** [comment]
보통 api스펙 상의 후 백에서 진행해 주시고 더 필요한 부분이 있으면 요청하는 쪽으로 했습니다! 특히 BFF패턴을 직접 짠 건 아니지만 하나의 api로 불러와야 할 때에도 백에 요청을 하여 연결된 데이터를 백에서 같이 보내주는 식으로 진행했습니다. 근데 이렇게 하다 보니 백엔드 요청 시간이 길어지게 되고 특정 endpoint를 불러오는 상황(요청 시간 길어지는 endpoint)의 경우 백에서 연결 데이터를 직접 가공해서 보내주시는 번거로움이... 생겼습니다.(물론 제 일은 아님)
api스펙의 경우 기획 > 프론트엔드 파악(기획, ERD파악 후) > 백에 특정 형식 요청 으로 진행했습니다!

**Comment by 2min0-dev** [comment]
### 기획 & 디자인이 있는 경우
1. 전달 받은 기획서 & 화면 정의서 각자 검토하며 기능 구현에 필요한 API 스펙 구상
2. 프론트 & 백 (& 기획에 논의가 필요할 경우 기획자도 같이) 리뷰 진행하며 API 스펙 논의
3. 개발 진행
4. API 스펙에이나 기능에 대한 수정 사항이 있는 경우 서로 요청하여 반영

### 기획 & 디자인이 없는 경우 (ex. 어드민)
1. 관계자들(ex. 서비스팀, 백엔드 개발자 등)과 논의하여 필요 기능 파악
2. 백엔드 개발자와 API 스펙 논의
3. 기존 프로젝트 중 유사한 프로젝트를 참고하여 개발 진행 (없으면 알아서)
4. API 스펙에이나 기능에 대한 수정 사항이 있는 경우 서로 요청하여 반영

위와 같은 방식으로 진행하고 있습니다!

**Comment by ghost** [comment]
저희 회사는 기획리뷰를 거친 뒤에 백엔드 담당자 분이 API를 개발하고 나면 스퀀스 다이어그램과 함께 이슈를 올려주십니다.

다이어그램을 참고하면서 프론트 쪽 개발하다가 API에 이슈가 있어서 코멘트를 달면 피드백을 주고받는 방향으로 이루어지고 있습니다~

![154110933-9bc0b8e6-f9e9-486a-afae-7cd0e9af3239](https://github.com/user-attachments/assets/b7e044cb-d025-4cfd-ba01-56671d5a3f92)

**Comment by Joie-Kim** [comment]
저희 프로젝트도 다양한 플랫폼을 지원하다 보니(Web, Android, iOS), 데스크탑과 모바일 화면에서 다른 데이터를 보여줘야 할 때.. 어쩔 수 없이 프론트엔드에서 연산을 해 사용해야 하더라구요.
> 예를 들어, 아래와 같은 경우에 API를 날짜 별 그룹화 한 버전으로 하나 더 만들 수 없으니, 어쩔 수 없이 프론트엔드 단에서 리스트를 그룹화 해야 하더라구요... (Map으로 날짜 키 마다 배열 생성...🤯)
>- 데스크탑 화면에서는 전체 리스트를 테이블 형태로 노출한다. (페이징이 있음)
>- 모바일 화면에서는 날짜 별로 그룹화 하여 "날짜(타이틀)+리스트" 형태로 반복해 노출한다. (페이징 없이 무한 스크롤 형태로 제공)

최근 진행하던 프로젝트에서 이런 일을 많이 겪다 보니.. BFF에 대해 관심이 생겼어요..
그러다 보니 서버 구축에도 관심이.. 생기고.. 점점 할 게 많아지고.. 😵 (꿱)
