### ISSUE TITLE
[5장] 프레임워크 없는 방식이라는 게 무엇인가?

### ISSUE THREAD

**Issue by Joie-Kim** [FE-StudyWithMe/FE-without-framework#32]
## 🧐 Question

"프레임워크 없는 방식으로 HTTP 클라이언트를 구축하는 방법을 알아보자."라고 말하며 5장이 시작되는데요, 그럼 '프레임워크 있는 방식'으로 만들어진 HTTP 클라이언트는 어떤 게 있을까요?
>- HTTP 클라이언트의 의미를 '웹 서버와의 통신을 위해 HTTP 요청을 보내고, 응답을 처리하는 도구'로 이해했고, 책에서 소개한 XMLHttpRequest, Fetch API, axios 그 자체가 될 수도, 이 녀석들을 나름(?) 커스텀한 `http.js`가 될 수도 있다고 생각했습니다.
>- 프레임워크 있는 방식의 HTTP 클라이언트는.. react-query와 같이 특정 프레임워크를 위한 라이브러리를 뜻하는 걸까요..?

**Comment by horang-e** [comment]
프레임워크 자체에 있는 HTTP  클라이언트를 사용하지 않고 개발하자! 이렇게 인지를 하고 넘어갔습니다. 그래서 찾아보니
### Angular
 Angular는 자체적으로 HttpClient라는 모듈을 제공합니다. 이는 Angular의 공식 HTTP 클라이언트입니다.
```js
// Angular HttpClient 사용 예시
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class UserService {
  constructor(private http: HttpClient) {}

  getUsers() {
    return this.http.get('/api/users');
  }

  createUser(user: User) {
    return this.http.post('/api/users', user);
  }
}
```
[Angular 공식 문서](https://v17.angular.io/api/common/http/HttpClient)
### Vue3
공식 권장하는 VueFetch (Nuxt의 useFetch)
```js
import { useFetch } from '@vueuse/core'

const { isFetching, error, data } = await useFetch(url)
```

이렇게 프레임워크 자체적인 HTTP클라이언트들이 있고 저자는 그걸 쓰지 않는 구축을 말한것이 아닌가..!생각합니다.

**Comment by ghost** [comment]
저도 서현님이 말씀하신 것처럼 특정 라이브러리나 프레임워크에 종속되지 않는 모듈을 만드는 방법으로 이해했습니다!
