### ISSUE TITLE
[5장] 미들웨어를 사용하시나요?

### ISSUE THREAD

**Issue by horang-e** [FE-StudyWithMe/FE-without-framework#34]
## 🧐 Question

여러분들은 미들웨어를 사용하시나요? 사용하신다면 어떤 이유에서 어떻게 사용하시나요?

저는 실무에서 미들웨어를 따로 사용하지 않고 미들웨어의 패턴을 띄는 axios의 interceptor를 사용했습니다.
```js
export const auth = axios.create({
  baseURL: "",
  headers: { "Content-Type": "application/json" },
});

auth.interceptors.request.use(
  (config) => {
    const { accessToken } = userStore();
    config.headers.Authorization = `Bearer ${accessToken}`;
    return config;
  },
  (error) => {
    return Promise.reject(error);
  },
);

auth.interceptors.response.use(
  (response) => {
    return response;
  },
  async (error) => {
    const originalRequest = error.config;
    const { setToken } = userStore.getState();

    if (error.response.status === 401 && !originalRequest._retry) {
      originalRequest._retry = true;
      const token = await retrieveAccessToken();
      setToken(token?.accessToken, token?.refreshToken);
      originalRequest.headers.Authorization = `Bearer ${token?.accessToken}`;
      return sparta_games(originalRequest);
    }
    return Promise.reject(error);
  },
);
```
사용 이유는
- request 시 config 추가
- response 토큰 에러 시 refreshToken을 사용한 토큰 리프레시 및 재 요청

> + 추가로 최근에 안 사실인데 axios는 Content-Type을 설정하지 않아도 자동으로 인식해서 변경해준다고 합니다!

## 📝 Reference
미들웨어 찾아보다가 nextjs 자체의 미들웨어도 있어서 한번 공유해봅니다.
[Nextjs의 미들웨어](https://reactnext-central.xyz/blog/nextjs/middleware)

**Comment by ghost** [comment]
전 직장에서 Express로 개발된 서비스 프론트를 짧게 담당한 적이 있는데, 그 프로젝트의 미들웨어 단에서 요청 메시지 헤더를 분석하여 A/B 테스트 로직을 구현했던 걸로 기억해요!

**Comment by chhw130** [comment]
저도 개인 프로젝트에서는 서현님과 동일하게 토큰 발급을 위한 용도로 `intercepter`를 사용했었습니다.

그 이외에는 next.js middleware를 이용해 routing guard를 구현해본 정도 밖에 없는거 같아요.(다양한 기능이 있는 걸로 아는데, 서버 개념이 들어가서 제대로 익혀보지는 못했어요...ㅋㅋ)
