### ISSUE TITLE
[5장] REST API vs RESTful API

### ISSUE THREAD

**Issue by 2min0-dev** [FE-StudyWithMe/FE-without-framework#35]
## 🧐 Question
책에 REST가 나와서 가져와 본 주제입니다!
저는 REST API와 RESTful API를 같은 의미로 사용하고 있었는데, 둘이 차이가 있다고 하더라구요.
실제 실무에서도두 단어가 혼용되어 많이 사용되고 있는데, 둘의 차이를 알아두면 좋을 것 같아 내용 정리해보아요:)

### REST API : **이론적인 원칙과 가이드라인**
- REpresentational State Transfer
- 웹 서비스를 디자인하고 개발하는 방법
- 클라이언트와 서버 간의 상호작용을 규정
- 여러가지 제약 조건들을 가짐
  >  - Client–server 구조 : 클라이언트와 서버는 서로 독립적이어야 하며, 클라이언트는 오직 URIs 리소스만 알아야한다. 클라이언트와 서버의 인터페이스가 변경되지 않는 한, 이 둘은 독립적으로 개발되거나 대체될 수 있게 유지해야한다. (관심사의 명확한 분리)
  >   - Stateless(무상태성) : 클라이언트의 모든 요청에는 해당 요청을 이해할 수 있는 모든 정보가 포함되어야한다. 서버는 HTTP 요청에 대한 어떤 것도 저장하지 않는다. 컨텍스트를 유지해야하는 세션, 인증과 인가에 대한 정보 또한 클라이언트에만 보관되며, 각 요청 시 해당 정보를 모두 포함하여 서버에 요청한다.
  >   - Cacheable : 서버는 Response cache-control 헤더에 해당 요청이 캐싱이 가능한 지에 대한 여부를 제공해야 한다. 이를 제공한다면 클라이언트는 Response를 캐싱하여 서버와 클라이언트 간의 상호작용을 줄이고, 성능과 서버 가용성을 늘릴 수 있다.
  >   - Uniform interface(일관된 인터페이스) : 보편적인 소프트웨어 엔지니어링 원칙을 component interface에 적용하면, 전체적인 시스템 아키텍처는 단순화되고 각 상호작용에 대한 가시성이 개선된다. 이름 그대로 일관된 인터페이스를 얻기 위해 REST에서는 4가지 인터페이스 규칙을 정의하였다.
  >     - identification of resources : 요청 시 개별 자원을 식별할 수 있어야함
  >     - manipulation of resources through representations : 어떤 자원에 대헤 작업하기 위한 적절한 표현과 메타데이터를 충분히 갖추고 있다면, 서버는 해당 자원을 변경, 삭제할 수 있는 정보를 가지고 있단 의미
  >     - self-descriptive messages : 자신을 어떻게 처리해야하는지 정보를 포함해야함
  >     - hypermedia as the engine of application state : 단순히 결과 뿐만이 아니라 결과에 대한 정보를 포함해야 함
  >   - Layered system(다중 계층) : REST는 다중 계층 구조를 가질 수 있도록 허용한다. (예를 들어 API 서버와 DB서버 그리고 인증 서버를 따로 둘 수 있도록). 그리고 각 레이어는 자기와 통신하는 컴포넌트 외 레이어에 대해서는 정보를 얻을 수 없다. 클라이언트는 REST 서버와만 상호작용할 뿐, REST가 상호작용하는 레이어나 그 외 중간 레이어들, end server에 직접적으로 요청할 수 없으며 이들의 상호작용 또한 볼 수 없다.
  >   - Code on demand (optional) : 서버가 클라이언트에서 실행시킬 수 있는 로직을 전송하여 클라이언트의 기능을 확장시킬 수 있다. 이를 통해 클라이언트가 사전에 구현해야하는 기능의 수를 줄여 간소화시킬 수 있다.

### RESTful API : **REST API의 이론적 원칙과 가이드를 적용한 API**
- REST 아키텍쳐 스타일을 따르는 웹 API

~~뭔가 찾아놓고 보니 큰 차이는 없는 것 같기도 하구~~

## 📝 Reference

- [[API/서버/백앤드]REST API vs RESTful API 비슷해보이는데 뭐가 달라??(파이썬,스위프트,코틀린 사용 예제코드 포함)](https://m.blog.naver.com/codingbarbie/223233477242)
- [REST란? REST API와 RESTful API의 차이점](https://dev-coco.tistory.com/97)
- [RESTful API를 위한 6가지 원칙과 네이밍](https://prohannah.tistory.com/156)
- [[ChatGPT] REST API와 RESTful API의 차이](https://poe.com/s/bQ3GJTt1XdOl8OTjrdQT)

**Comment by Joie-Kim** [comment]
REST는 아키텍처 구성  방식인 거 같고, RESTful API는 그 방식을 지켜 만든 API를 말하는 거 같네요!? 😯
책에서는 HTTP 클라이언트 만드는 걸 설명하기 위해서, 위에 적어주신 것 중에 **Client–server 구조**에 초점을 맞춰서 짧게 설명하고 넘어간 거 같아요..!

**Comment by chhw130** [comment]
@Raihyul 
저도 실무에서 같은 의미로만 파악하고 혼용하여 사용했는데, 명확하게 구분해서 알고 있으면 좋을거 같네요!

- REST : 리소스들을 이름으로 구분하고, 이 자원의 형태를 주고 받는 아키텍쳐.
- RESTful : REST원칙으로 잘 설계된 API

물론.. 큰 차이는 없어서, 딥하게 논의되는 사항이 아니면 그냥 혼용해서 사용할 것 같습니다 ㅋㅋㅋ
