### ISSUE TITLE
[5장] http통신을 통해 테스트 관련해서 질문입니다!

### ISSUE THREAD

**Issue by chhw130** [FE-StudyWithMe/FE-without-framework#36]
## 🧐 Question
이번에 http통신을 통해 컨트롤러와 모델 등을 분리하여 테스트하기 쉽게 만들었다는 말이 많이 나와서 질문드립니다!

저번 항플 과정에서 msw를 모킹한 것을 기반으로 테스트했던 것 기억나시나요?? 이 과정에서 독립적으로 테스트하려면, 테스트마다 간섭이 나지 않기 위해 많은 시도를 했지만 해결되지 않았습니다.
결국 아래와 같이 데이터를 비워주는 함수를 테스트전(beforeAll)에 실행시켜 해결해주었는데요.

```javascript
describe('일정 CRUD 및 기본 기능', () => {
    beforeEach(resetEvents); // here
    test('새로운 일정을 생성하고 모든 필드가 정확히 저장되는지 확인한다', async () => {
      const TEST_EVENT = {
        title: '새로운 일정',
        date: '2024-08-01',
        startTime: '14:30',
        endTime: '15:30',
        description: '새로운 일정 설명',
        location: '서울대입구역',
        category: '업무',
      };
```
하지만 오프 코치님께서 아래와 같은 문제를 말씀해주셨는데, 그 때 개선방법을 알려주셨는데 혹시 기억하시는 분 계신가요!!?

## 📝 Reference

<img width="853" alt="스크린샷 2024-10-27 오후 2 51 29" src="https://github.com/user-attachments/assets/9307152a-f572-45a0-937f-1d833a3a9b15">

**Comment by Joie-Kim** [comment]
저도 저렇게 해결을 하고, 준일 코치님 멘토링 때 '찝찝한 해결 방법'이라고 말씀 드렸더니,
"그렇게 해결해야 해요"라고 해주셨던 걸로 기억합니다........ 😵‍💫
당시 적었던 노션에도 별 말이 안 적혀있는 거 보니, 저는 저 방법 외 해결책에 대해 듣지 못 했던 거 같아요.................
