### ISSUE TITLE
[etc] 주니어 프론트엔드 개발자에게 3개의 태스크가 동시에 주어진다면?

### ISSUE THREAD

**Issue by horang-e** [FE-StudyWithMe/FE-without-framework#37]
## 🧐 Question
이 이슈는 제가 최근에 링크드인에 기억에 남는 면접 질문에 대한 내용을 올렸었는데 초원님이 같이 얘기해봤으면 좋겠다고 공유해달라 하셔서 한번 가져와봤습니다! 

이전에 면접 질문중에 
A: “만약 당신에게 3개의 테스크가 동시에 주어진다면 어떤 순서로 처리하시겠습니까?“
나: ”저는 비즈니스 로직 상 중요한 테스크 부터 수행할것 같습니다!“
A: "셋 다 중요하다면요?"
나: (당황)“어...재밌는 개발부터 할것...같습니다(?)”
A: "(ㅎㅎ) MBTI P 이신가요 ㅎㅎ"
나:“아녀... J 입니다....”

저는 저렇게 대답했고 망했다.. 생각을 했었거든요 ㅋㅋㅋ🥲
저러고 나서 나중에 혼자 어떻게 답변하는게 좋았을까? 했을 때는 "세 태스크의 상관관계를 파악하고 우선 되어야할게 있다면 그 순서대로 진행하고 만약 셋다 별개의 태스크라면 러닝커브가 짧은 개발부터 진행한다." 라고 좀 있어보이게(?) 말해야겠다! 라고 생각했어요. 

여러분이라면 어떤 답변을 하셨을것 같으신가요?.?

참고로 초원님이 댓글로 답변 달아주신거 보고 내가 인사 담당자였다면 무조건 초원님을 뽑겠다 생각했어요! 그래서 앞으로 같은 질문 나오면 초원님 답변 손민수를...
<img width="550" alt="스크린샷 2024-11-01 오후 6 40 54" src="https://github.com/user-attachments/assets/9c67dbb5-0a31-44b0-944b-e0399b16d775">

**Comment by chhw130** [comment]
@horang-e 
링크드인에 작성해주신 글 봤습니다...ㅋㅋ
저도 초원님이랑 생각이 같습니다. 제가 하고 있는 작업이 다른 누군가와 얽혀있다면 그 작업을 우선순위로 수행하는게 맞지 않나 싶어요!
사람이 늘어 날수록 소통해야하는 이해관계도 늘어나기 때문이죠.

이걸 약간의 공식으로 생각하면..
> N을 함께 작업하는 사람 수라고 가정하면
> 소통 경로 = `N(N - 1) / 2`
> 즉 4명이면 소통 경로는 6개나 되는거죠..

이해관계자가 많아질수록 커뮤니케이션의 복잡성이 급격히 증가하기 때문에, 서로 얽힌 작업은 우선적으로 다루는 것이 효율적인 거 같아요 ㅎ

**Comment by kimfield98** [comment]
서현님, 제 답변 손민수라니 .. 영광인걸요 .. 전 여러분 스터디 답변을 주섬주섬 .. 🤣🤣
언제나 한 번쯤 생각해보면 좋은 질문들을 많이 던져주셔서 감사해요!
덕분에 고민하고 더 성장할 수 있는 환경에서 지내고 있답니다아 .. ❤️

**Comment by ghost** [comment]
프론트엔드 개발자는 서비스의 가장 앞단을 담당하다 보니 백엔드, 기획, 디자이너, 인프라 등의 다양한 영역을 걸쳐서 소통하기 때문에 대부분의 태스크가 적어도 1개의 영역과 얽히는 것 같아요.

지금 고객 VoC 대응하느라 수정요청이 한번에 5개씩 오기도 하는데, 저는 기획자 분께 언제까지 마무리 지으면 되는지 여쭤보고 모두가 참고할 수 있도록 이슈를 생성해서 코멘트로 남겨달라고 요청을 드립니다.

그리고 피드백에 맞춰 태스크의 우선순위를 정리해서 급한 건부터 해결해 나가고 있습니다!

**Comment by Joie-Kim** [comment]
프론트엔드 개발자이다 보니까, 업무가 오면 기획자분이나 디자이너 분과 논의할 일이 많아지는데요(사실 저는 사업팀과 이야기 하기도 합니다..)..
다른 분들이 말씀 해주신 대로 유관 부서와의 협의를 먼저 진행하고, 그 답변이 오는 걸 기다리면서 혼자 처리할  수 있는 일을 하는 거 같아요.
병렬적으로 수행한다고 할 수도 있겠네요..? 🤔 데드라인은 정말....... (할말하않)

**Comment by 2min0-dev** [comment]
다른 분들이 이미 좋은 답변들을 달아주셨네요:)
저는 보통 이 순서대로 진행하는 것 같습니다!

1. 데드라인을 파악하여 급한 순서대로 처리
2. 데드라인이 비슷하면 QA 진행 시 논의 및 수정 사항이 많을 것으로 예상되는 테스크 순서대로 처리 (보통 관련 부서 및 직원 수가 많거나 정의된 기능에 애매한 부분이 있는 경우)
3. 앞의 기준들이 다 비슷하면 일찍 끝낼 수 있는 것 부터 처리
4. 생각해봐도 잘 모르겠다 싶으면 팀장님 찾아가서 우선 순위 논의하기 (그러라고 계신 팀장님이니까 😁)
