### ISSUE TITLE
[6장] React.Fragment를 아시나요?

### ISSUE THREAD

**Issue by horang-e** [FE-StudyWithMe/FE-without-framework#39]
## 🧐 Question

전 책을 읽다가 '프래그먼트' 라는 단어에 꽂혀서 React.Fragment를 자주 사용하는데 얘가 다른 div랑 무슨 차이인지가 너무 궁금해졌습니다. 그래서 찾아보니 개발 초기에 자주 보이는 에러인 

`
Failed to compile.
./src/App.js
Line 6:  Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>..</>?`
이 놈 때문이였는데요. 

```js
return(
<div>hi</div>
<div>bye</div>
)
```
이렇게 코드를 치면 위와 같은 에러가 발생하게 됩니다. 
이처럼 최상위 태그가 있어야만 동작하는 이유는 자바스크립트는 두 개 이상 리턴하지 못하기 때문입니다.
```js
//이러면 안됨!
return (
    React.createElement('div', {}, 'hi')
    React.createElement('div', {}, 'bye')
);
```
그렇기 때문에 최상위 태그가 반드시 필요한거죠! 근데 저 태그를 감싸기 위해서 <div> 태그를 감싸준다고 하면? 추가적인 노드가 생성됩니다. 근데 노드를 만들고 싶지 않으면? 그 때 사용하는것이 바로 Fragment 태그입니다. Fragment 태그는 최상위 태그로서 작동하고 key 값 또한 추가 할 수 있지만 노드를 생성하진 않는다고 합니다. 너무 신기하지않나여...🥹
```js
return (
  <div>
    <div>hi</div>
    <div>bye</div>
  </div>
);
//리액트 엔진이 해석
return (
  React.createElement('div', null,
    React.createElement('div', null, 'hi'),
    React.createElement('div', null, 'bye')
  )
);
```
```js
return (
  <Fragment>
    <div>hi</div>
    <div>bye</div>
  </Fragment>
);
//리액트 엔진이 해석
return (
  React.createElement(React.Fragment, null,
    React.createElement('div', {}, 'hi'),
    React.createElement('div', {}, 'bye')
  )
);
```

레퍼런스에 있는 예시들을 보니까 앞으로 저도 개발할때 해당 태그를 많이 사용해야겠단 생각을 했답니다!

## 📝 Reference
[리액트 프래그먼트의 모든것(굉장히 흥미로움)](https://www.memberstack.com/blog/react-fragment)

**Comment by kimfield98** [comment]
저는 React 개발할 때 컴포넌트를 감싸야 하는 경우 Fragment(<></>)를 자주 사용하는데요, 
단순히 "불필요한 div가 코드를 지저분하게 하네... 다른 필요한 정보를 읽는데 방해가 된다"라는 생각이었던 것 같아요.

Fragment가 추가 DOM 노드를 생성하지 않는다는 걸 항해플러스 자바스크립트/리액트 주차 때 알게 되었는데, 
이번 이슈를 통해 한 번 더 상기하게 되었어요 :)

컴퓨터 입장에서 "오 노드 안만들어도 돼서 너무 좋아요" 이렇게 말해주면 공감도 되고 더 신경써줄텐데 .. 크크
앞으로 더 의미있게 Fragment를 사용해줄게 .. 😜😜
