### ISSUE TITLE
[6장] 쿼리 파라미터 방식이 필요한 경우?

### ISSUE THREAD

**Issue by horang-e** [FE-StudyWithMe/FE-without-framework#40]
## 🧐 Question

현우님이 이미 PR에 사용하는 케이스 에 대해 간단히 정리해 주셨지만 실제 실무에서 어떤 상황, 어떤 서비스에 쿼리 파라미터를 사용하시는지 궁금합니다!

저 같은 경우는 기존 서비스에 공유 가능한 결제 링크를 생성할 때 쿼리 파라미터를 사용하여 결제를 진행했었습니다. 
`/pay_link?name='누구'&price='가격'&product='상품'&...등등의 결제정보`

하지만 혹시 전화번호와 같은 민감한 부분이 노출될 가능성이 있다고 판단되어 링크 생성시 데이터를 서버에 보내고 그 아이디를 받아서 해당 id를 포함한 경로 세그먼트 방식으로 변경을 했습니다.
그 때 당시에는 막연히 그냥 보안상의 문제가 있을 수 있다. 정도였지만 찾아보니 검색 엔진에서도 그 데이터를 가지고 온다고 하니 기존 서비스처럼 링크 생성 했다면 구글에 제 번호 검색하면 나왔을 수도 있겠다는 생각이 드네요🫨

검색 조건 지정, 필터링 이외에 쿼리 파라미터 방식을 사용하는 경우도 있을 것 같은데 여러분들은 어떤 이유 때문에 쿼리 파라미터를 사용하시나요?

## 📝 Reference

[SEO와 쿼리파라미터](https://velog.io/@timosean/Web-Path-variable-Query-String-%EA%B7%B8%EB%A6%AC%EA%B3%A0-SEO)

**Comment by kimfield98** [comment]
오 .. 정말 코드를 돌아보니 실제로 사용했던 쿼리 파라미터 케이스가 생각보다 단순했네요!

- 검색 필터링
- 페이지네이션
- 정렬 조건

추가로 생각해보니 Tabs 컴포넌트 조작할 때 쿼리 파라미터를 활용하여 현재 활성화된 탭 상태를 URL에 반영해서 관리했던 것 같아요 🤔

**Comment by ghost** [comment]
저는 개발하면서 특정 페이지 A에서 B로 이동하면서 전달해야 하는 데이터를 전역상태 대신 URL query에 자주 명시했던 것 같아요!

**Comment by Joie-Kim** [comment]
저도 초원님이랑 비슷하게 1) 검색 필터 2) 페이지네이션에서 주로 사용했습니다..!
주로 간단(?)하고 노출 되어도 무관한 데이터들 위주로 전달을 했던 거 같아요.

**Comment by chhw130** [comment]
저도 노출되어도 괜찮은 부분들만 쿼리파라미터로 필터링 기능을 구현했었습니다.
추가로 다른 개발자분이 쿼리 파라미터로 전역 상태관리 하는 글을 봐서 공유드립니다!
[url로 전역 상태 관리하기](https://velog.io/@k-svelte-master/react-state-with-query)
