### ISSUE TITLE
[6장] 복잡한 네비게이션 시나리오에서 어떤 라우팅 방식을 사용하는 것이 좋을까?

### ISSUE THREAD

**Issue by kimfield98** [FE-StudyWithMe/FE-without-framework#41]
## 🧐 Question

이번 장에서 라우터의 동작 원리를 배우면서, 제가 최근 겪었던 라우팅 이슈가 떠올랐는데요.

목록 페이지에서 페이지네이션과 필터링 상태를 URL로 관리하고 있었습니다
(예시) /products?page=2&category=electronics&sort=price

여기서 특정 상품을 클릭하면 상세 페이지로 이동하는데, 상세 페이지의 탭 활성화 상태도 URL로 관리하고 있었어요.
(예시) /products/123?tab=reviews

문제는 사용자가 뒤로가기를 눌렀을 때였습니다. 
목록 페이지의 이전 필터링/페이지네이션 상태를 유지하면서 자연스러운 네비게이션을 구현하는 게 생각보다 까다로웠거든요.

팀 내에서 useState 사용을 최소화하고자 하는 합의가 있어 URL로 상태를 관리하려 했는데, 
이런 복잡한 네비게이션 시나리오에서는 어떤 접근 방식이 좋은 선택이었을까요? 다들 이런 상황을 어떻게 처리하시나요! 👀

**Comment by ghost** [comment]
제가 한달 전에 메일링크를 통해 접속하는 페이지를 개발했는데, 경로 매개변수와 query key를 합쳐서 한 7개 되는 긴 URL을 가지고 있었어요.

어차피 이 화면 자체가 다른 영역에서 사용되진 않아서 URL로 전달된 경로 인자나 query 값을 렌더링되는 컴포넌트의 props로 전달하는 방식으로 구현했습니다!

이 부분은 [Vue Router 내장 기능](https://router.vuejs.org/guide/essentials/passing-props.html#Function-mode)을 활용했습니다~

**Comment by Joie-Kim** [comment]
저희는 history를 유지할 수 있는 composable(react의 hook)을 만들어서 사용했습니다.
URL의 query param이 유지될 수 있도록 로직을 작성했습니다. (관련 코드 찾아보고 첨부 가능하면 할게요!)
