### ISSUE TITLE
[6장] 라우팅과 데이터 패칭 전략

### ISSUE THREAD

**Issue by kimfield98** [FE-StudyWithMe/FE-without-framework#42]
## 🧐 Question

이번 학습메이트 채점을 하면서 아래 기준들을 보고 라우팅과 연결해서 고민해보면 좋을 것 같다는 생각이 들었습니다!

> **심화과제 요구사항**
> 1. 모든 API 호출을 TanStack Query의 useQuery/useMutation으로 대체
> 2. 적절한 쿼리 키 설정
> 3. useState 대신 선언적인 프로그래밍 적용
> 4. 캐싱과 리프레시 전략

<br />

특히 라우팅은 데이터 패칭과 밀접한 관계가 있다고 생각하는데요,
예를 들어 공지사항 목록에서 상세 페이지로 이동할 때: `/notices?category=general -> /notices/123`

```js
// 목록에서 뒤로가기 했을 때 즉시 데이터를 보여주기 위해
const { data: notices } = useQuery({
  queryKey: ['notices', category],
  queryFn: fetchNotices,
  staleTime: 5 * 60 * 1000,  // 5분간 리패칭 없이 캐시 활용
  cacheTime: 10 * 60 * 1000  // 10분간 캐시 유지
});
```

```js
// 공지사항에 hover시 상세 데이터 미리 준비
const queryClient = useQueryClient();
const handleHover = (noticeId: string) => {
  queryClient.prefetchQuery({
    queryKey: ['notice', noticeId],
    queryFn: () => fetchNotice(noticeId)
  });
};
```

```js
// 상세 페이지
const { data: noticeDetail } = useQuery({
  queryKey: ['notice', id],
  queryFn: () => fetchNotice(id),
  // 목록에서 받은 기본 데이터로 즉시 표시
  placeholderData: (prev) => 
    prev?.notices?.find(n => n.id === id)
});
```

라우팅과 데이터패칭을 연관지어 고민한다면 사용자 경험을 훨씬 개선시킬 수 있을 것 같아요.

- 뒤로가기 시 로딩 없이 즉시 목록 표시
- 공지사항에 hover만 해도 상세 페이지 전환이 빨라짐
- 상세 페이지 진입 시 제목이나 요약 정보라도 먼저 보여줄 수 있음

여러분들은 라우팅과 데이터 패칭을 어떻게 설계하시나요? 
또 TanStack Query의 기능들을 활용한 경험이 있다면 공유 부탁드려요 😄

**Comment by chhw130** [comment]
Tanstack에서 제공하는 기능은 사실 querykey에 기반해 캐싱하고 있는 것이라 생각합니다.

오히려 진짜 url에 기반하여 최적화를 이뤄지고 있는 부분은 next.js라 생각해요.
Next.js에서는 폴더 기반 라우팅과 함께 fetch api로(ISR,SSR,SSG) 및 prefetching을 구현하며 사용자 경험을 향상시킬 만큼 강력한 캐싱 기능을 제공하고 있어요. 그래서 Next.js를 사용하고 있는 분들의 의견 중에 굳이 Next에 tanstack을 도입해야 하는 말도 있었어요!

<img width="740" alt="스크린샷 2024-11-03 오후 8 48 50" src="https://github.com/user-attachments/assets/47619ff2-0218-45b2-8d4b-8c94f7310432">

Ref
[Next.js prefetch](https://parkgang.github.io/blog/2023/07/15/how-nextjs-prefetch-work/)
[Next.js에서 fetching과 tanstack](https://blog.toktokhan.dev/how-to-use-effectivelynext-js-fetchtanstack-query-333c28168e92)
