### ISSUE TITLE
[6장] router replace

### ISSUE THREAD

**Issue by 2min0-dev** [FE-StudyWithMe/FE-without-framework#43]
## 🧐 Question
여러분은 React Router 혹은 Vue Router에서 제공되는 replace 기능을 써보셨나요??
저는 특정 프로젝트에서 뒤로가기 기능이 아예 제한되어야 해서 해당 기능을 사용해보았는데요.
다른 분들은 어떤 경우에서 replace를 써보았는지, 뒤로가기 기능을 제한해야 한다면 어떤 방식을 사용하실 것 같은지 같이 얘기 나눠보고 싶어요!

## 📝 Reference

[History.replaceState()](https://developer.mozilla.org/ko/docs/Web/API/History/replaceState)
[React Router replace](https://reactrouter.com/en/main/fetch/replace)
[Vue Router replace](https://v3.router.vuejs.org/kr/api/#replace)

**Comment by ghost** [comment]
>다른 분들은 어떤 경우에서 replace를 써보았는지,

전 대부분 `push` 메서드만 사용했던 것 같아요!

>뒤로가기 기능을 제한해야 한다면 어떤 방식을 사용하실 것 같은지 같이 얘기 나눠보고 싶어요!

특정 화면을 뒤로 가기로 접근할 수 있는 경로를 모두 분석해서 [Vue Router의 Naviagtion Guard](https://router.vuejs.org/guide/advanced/navigation-guards.html#Per-Route-Guard)를 통해 필터링을 하는 것도 하나의 방법이 될 것 같아요! 

저는 회사에서 개발할 때 [컴포넌트 단위 Navigation Guard](https://router.vuejs.org/guide/advanced/navigation-guards.html#In-Component-Guards) 기능을 유용하게 사용하고 있습니다~

**Comment by Joie-Kim** [comment]
저는 '이전 페이지로 돌아가야 한다'하면 push를, '이전 페이지를 무시(?)해야 한다'고 하면 replace를 사용했습니다.
가령 로그인 페이지 같은 경우는 로그인 이후에 뒤로 가기 버튼을 눌렀다고 로그인 페이지로 이동을 해야하는 건 아니잖아요.
두 가지 메소드에 분명한 차이가 있어서 의도에 맞게 사용했던 거 같습니다! :D

**Comment by chhw130** [comment]
저 또한 희주님처럼 replace같은 경우 로그인 인증 여부에 따라 불필요하게 라우팅 되지 않도록 replace메서드를 사용했었습니다!

> 로그인후 -> 로그인 페이지로 이동하지 못하게
> 결제 완료 후 -> 기존 결제 정보 페이지로 이동하지 못하게
