### ISSUE TITLE
[etc] 정규표현식

### ISSUE THREAD

**Issue by 2min0-dev** [FE-StudyWithMe/FE-without-framework#44]
## 🧐 Question
6장으로 타이틀 달기는 약간 애매해서 etc로 넣었습니다!
이번에 정규 표현식을 사용하는 부분이 나와서, 제가 정규 표현식 사용할 때 참고하는 사이트들 공유드리려구 작성해보는 글입니당:)

### [📚 JavaScript 정규 표현식 문법 총정리 + 응용 예제](https://inpa.tistory.com/entry/JS-%F0%9F%93%9A-%EC%A0%95%EA%B7%9C%EC%8B%9D-RegExp-%EB%88%84%EA%B5%AC%EB%82%98-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-%EC%89%BD%EA%B2%8C-%EC%A0%95%EB%A6%AC)
정규 표현식 문법 참고할 때 보는 페이지입니다!
정규식 기호 모음 부분으로 가면 표로 깔끔하게 정리되어 있어서 참고하기 편해요:)
_인파 최고 (소근소근)_

### [💻 정규식(Regex) 테스트 사이트 모음 (+ 사용 방법)](https://inpa.tistory.com/entry/%F0%9F%92%BB-%EC%A0%95%EA%B7%9C%EC%8B%9D-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%82%AC%EC%9D%B4%ED%8A%B8-%F0%9F%8E%81-%EB%AA%A8%EC%9D%8C)
정규 표현식 테스트 사이트가 모아져있습니당
저는 여기에서 가장 첫 번째 페이지인 [Regexr 사이트](https://regexr.com/)를 가장 많이 써요!
다른 사이트들도 많으니 나중에 정규 표현식 사용하시게 될 때 참고하시면 좋을 것 같습니당:)

이 외에 좋은 사이트나 글 있으면 같이 공유해봐요!
추가적으로 프로젝트에서 정규 표현식을 썼던 경우에 대해서도 같이 얘기 나눠보면 좋을 것 같아요:)

**Comment by chhw130** [comment]
사실 정규표현식이 필요한 경우(유효성 검사, 타입 변환), ai도움을 받아 빠르게 처리한 경험 위주인 거 같아요..ㅎㅎ😅
어느 정도 알고 있으면 도움이 될 거 같다는 생각이 들기는 하는데, 개인적인 의견으로는 이걸 굳이 공부해야 될거라는 의문이 들어요..ㅜ

**Comment by kimfield98** [comment]
저도 정규표현식은 AI에게  ..... 믿고 .. 맡깁니다 ..

**Comment by ghost** [comment]
저도 검색하고 나서 Regexr에 넣어서 실제로 맞는지 확인하고 있습니다ㅎㅎ
