### ISSUE TITLE
[6장] SEO를 고려하며 라우팅 하시나요?

### ISSUE THREAD

**Issue by Joie-Kim** [FE-StudyWithMe/FE-without-framework#46]
## 🧐 Question
(창을 닫아버려서 다시 쓰는 질문... 하.. 지난 주부터 저 왜 이러죠?)

- 다들 라우터를 구성하실 때(그러니까 URL 구조를 짜실 때), SEO에 대해 고려 하시나요?
- 제가 담당 중인 프로젝트는 SEO가 중요하지 않아서, 유저에게 직접 전달되는 서비스를 만드는 분들은 어떻게 고려하고 계신지 궁금합니다!
>- 저는 '점주' 분들이 사용하시는 관리 서비스를 맡아 개발 중이라.. 검색 엔진 최적화가 중요하지 않습니디.. 점주 계정이 아니면 접근도 안 돼요..... 😮‍💨

## 📝 Reference

- [해시? 히스토리?](https://jake-seo-dev.tistory.com/743)
- [seo 최적화 경로?...](https://saurabh80.medium.com/seo-friendly-route-in-reactjs-bc0d01332dd4)

**Comment by kimfield98** [comment]
아직은 멀고 먼 SEO .............
