### ISSUE TITLE
[공지] 7주차 발표

### ISSUE THREAD

**Issue by chhw130** [FE-StudyWithMe/FE-without-framework#47]
## 공지
- 발표는 10분내외로 학습했던 책 내용을 기반으로 합니다.
- 발표의 방향성은 자유롭게 해주시면 됩니다.
- 발표 자료들은 지금 레포지토리에 모두 오픈되어 올릴 생각입니다.
- 발표 이외의 활동으로 간단하게 스몰토크를 생각하고 있습니다. 주제도 하나씩 생각해 와주세요! (Ref: #37)

**발표내용이나 주제가 안겹치도록 미리 댓글로 발표 주제를 남겨주세요.**

**Comment by kimfield98** [comment]
<발표주제>
React Router의 내부 동작 원리와 브라우저 API

<스몰토크>
이번 스터디가 끝나고 무엇을 더 공부하고 싶나요?

**Comment by horang-e** [comment]
<발표주제>
함수와 메모리 관리

<스몰토크>
여러분이 프론트엔드 개발자로서 가장 관심있어 하는 영역은?(ex> SEO, 애니메이션, CI/CD 등)

**Comment by chhw130** [comment]
<발표주제>
리액트는 이벤트를 왜 이렇게 관리하고 있나요?

<스몰토크>
- 이직은 배신이다??
- [개발자가 겪는 가면 증후근](https://www.youtube.com/watch?v=hU4kULhOdNE&t=77s)

**Comment by ghost** [comment]
<발표주제>
- 프레임워크 없이 상태를 관리하는 방법

<스몰토크>
- 내가 만일 팀장이 된다면 제일 먼저 고치거나 구축하고 싶은 것은 무엇인가요?

**Comment by Joie-Kim** [comment]
<발표주제>

- SPA에서 히스토리를 관리하는 방법

<스몰토크>

- 어떤 개발자가 되고 싶은가요?
>- 개발자로서 어떤 컨셉의 자아를 가지고 싶으신가요!?
- 일 잘하는 개발자란 어떤 사람일까요?

**Comment by 2min0-dev** [comment]
<발표주제>
- 내가 생각한 이 책의 이야기

<스몰토크>
- 데이터의 가공을 어디에서 처리하는 것이 더 효율적일까요?
