### ISSUE TITLE
[2장] 렌더링

### ISSUE THREAD

**Issue by Joie-Kim** [FE-StudyWithMe/FE-without-framework#5]
## 🧐 Question

- 이번에도 엄청나게 간단하고 정말 궁금해서 이야기 나눠보고 싶은 질문입니다... (주절주절...ㅎ)
- 렌더링 성능에 대해서 추적하는 방법을 책에서 소개했는데, 여러분은 현업 혹은 사이드 프로젝트에서 해당 방법으로 성능을 측정해보신 적이 있나요!?
>- 저의 요즘 고민이 '성능 측정을 해본 경험이 없다'여서, 다른 분들은 어떠신지 궁금했습니다...

**Comment by ghost** [comment]
저도 따로 성능지표를 측정해본 적은 없었어요;

그냥 호기심에 Lighthouse로 지표들만 살펴본 정도로 그쳤던 것 같아요.

**Comment by horang-e** [comment]
저도 라이트하우스로 지표 살펴봤던게 다였던 것 같습니다..

요즘 이력서 피드백이나 특강 같은거 들으면서 진짜 현업할때 변태처럼 성능 측정 기록해봐야겠다.. 라는 생각을 하고 있긴 했습니다! 그 수치로 보이는 뿌듯함 + 이력서에 추가할 내용 갓챠까지 👍

**Comment by kimfield98** [comment]
얼른 .. 만들고 있는 제품이 완성돼서 성능 체크해보고 싶어요 선배님들 🥹
