### ISSUE TITLE
[etc] 코드의 가독성을 위해 재사용성이 없는 함수를 composable화(hook) 하는 게 좋은 방식일까요?

### ISSUE THREAD

**Issue by 2min0-dev** [FE-StudyWithMe/FE-without-framework#53]
## 🧐 Question
> 디자인을 향상시키는 첫 번째 단계는 이 코드를 별도의 파일로 옮기는 것이다.

7장의 초반에 나왔던 문장인데, 저는 이 문장을 보고 가장 먼저 생각난 것이 '가독성 향상' 이었어요.
그리고 이어서 최근 제가 작업했던 프로젝트에서 했던 고민이 떠올라서 다른 분들은 이 상황에 대해 어떤 생각을 가지고 계실지 궁금해 질문 올려보아요!

### 현재 상황
- 컴포넌트 구성
  - 화면 컴포넌트 A
  - matter.js를 사용하여 물체가 낙하하는 화면을 구현하는 컴포넌트 B
  - 사용자의 응답을 받을 버튼 컴포넌트 C
  - 컴포넌트 A가 부모, 컴포넌트 B와 C가 자식으로 A 내부에 위치
- 컴포넌트 B 내부 함수
  - matter.js 및 레벨 별 문제 초기 세팅 (함수 두개 정도)
  - 컴포넌트 C에서 발생한 유저 인터렉션에 따라 matter.js 내의 물체 처리 로직 (함수 세개 정도)
  - template 코드는 10줄도 되지 않는데 script 부분이 길어져 600줄 이상의 코드가 한 컴포넌트 내에 작성

### 고민사항
가독성을 생각하면 컴포넌트 B에 있는 함수들을 외부로 분리하는 것이 맞는 것 같아요.
하지만 통상 composable(React에서는 hook)은 재사용성이 고려되어야 한다고 생각하는 것에 반해 해당 함수들은 재사용성 없이 해당 컴포넌트에서만 사용되는 함수들이라 적합하지 않나 라는  생각도 들어요 🤔
여러분은 이러한 상황에서 어떻게 하실 것 같나요??
- 재사용성이 없어도 가독성을 위해 composable(hook)으로 분리
- composable의 개념에 중점을 두어 사용하지 않고 컴포넌트 B에 모두 작성
- composable을 사용하지 않고 외부로 분리 (이러한 경우엔 코드를 어디에 작성해야할까요?)

**Comment by horang-e** [comment]
만약 재사용성이 없는,컴포넌트 B 내부에서만 사용하는 함수의 경우에는 말씀하신것 처럼 컴포넌트 내부에 작성하는게 맞다고 생각합니다! 다만 코드의 가독성때문에 고민하시는 거라면 function 파일을 따로 만들어 분리해보는것도 좋지 않을까..? 하는 생각을 해봅니다! 왜냐면 문제 초기세팅이 정확히 어떤 의도인지는 모르겠지만 변경이 많이 없는 함수의 경우 어떻게 보면 config라고 생각하기 때문이랍니다!

**Comment by chhw130** [comment]
저라면 `재사용성이 없어도 가독성을 위해 composable(hook)으로 분리`를 선택할 거 같네요.

사실, React의 훅이나 Vue의 composable은 원래 재사용성을 목적으로 탄생한 것으로 알고 있어요. 그러나 요즘에는 비즈니스 로직이나 관심사 분리를 위해 사용하여, 코드의 가독성을 높이고 테스트가 용이해지는 장점을 얻는 경우가 많아진 것 같습니다!

**Comment by Joie-Kim** [comment]
저희 팀은 가독성을 높이기 위해서 분리하고 있는데, 공통으로 사용되는 composable과 페이지에서 사용되는 composable(상태 관리를 위한 코드)을 분리해 관리 중입니다.. 키키..

**Comment by ghost** [comment]
composable의 기능은 재사용성도 있지만 연관된 상태와 상태 로직을 그루핑하는 것도 있다고 생각해요!

composable 단위로 나누면 코드의 길이도 줄어들면서 가독성도 높아질 것 같습니다.

컴포넌트 단에서만 사용할 기능이 나중에 보니까 다른 영역에서도 활용될 수도 있어서 정의해두는 것도 괜찮을 것 같습니다~

**Comment by kimfield98** [comment]
저는 재사용성을 위한 hook들을 폴더 최상단 hooks 폴더 내에 위치시키고,
재사용성은 없더라도 가독성이나 로직 분리를 위해서는 해당 폴더 내 hooks 폴더로 분리하는 편입니다!
(만약 폴더 이름이 orders면 일단 useOrders.ts로 다 분리해두고 .. 그 다음 훅을 역할에 맞게 분리 .. 반복된다면 루트 hooks..)
