### ISSUE TITLE
[8장] 8장 정리 및 ADR/LADR?

### ISSUE THREAD

**Issue by horang-e** [FE-StudyWithMe/FE-without-framework#55]
### 안티패턴(실제 많이 사용되는 패턴이지만 비효율적이거나 비생산적인 패턴)
- 기술스택의 선택
	- 노후화에 대한 두려움
		- 너무 "빨리 변화는 기술의 변화에 이미 구식인가?" 하는 두려움을 느낌
		- 프레임 워크의 인기와 수명은 상관 없다
		- 앵귤러는 엄청났지만 엄청나게 사라졌다.
	- 언제가 레거시가 되는지?
	  - 새로운 비즈니스 요구를 수용하지 못하게 될 때
		- 새로운 개발자가 필요하지만 소프트웨어의 오래된 스택 때문에 작업할 수 있는 개발자를 찾을 수 없을 때
	- 스트랭글 애플리케이션 패턴
	  - 리팩토링 방법
		- 새 애플리케이션을 기존 애플리케이션에 추가
		- 기존 애플리케이션이 사라지게 될 때 까지 몇년동안 새 애플리케이션이 성장![스크린샷 2024-11-10 오후 3 18 04](https://github.com/user-attachments/assets/8fec17e1-c926-48b5-aa29-31764d3d6ef8)
	- 하이프 곡선 따르기
	- 일반적인 경로
		- 기존에 성공한 프로젝트 케이스에 편승하여 또 똑같은 프레임워크를 선택한다.
	- 전문가
		- 모든 기술 결정이 전문가에 의해 이뤄진다.
		- 위험한 방식이다. 협력을 통해 정해야한다!
	- 분노 주도 결정(ㅋㅋ꙼̈ 😡)
		- 실패가 잦은 팀의 경우 일어나는 의사결정
### 프레임워크 없는 운동 선언문
- 첫번째
  - 소프트웨어의 가치는 코드 자체가 아니고 왜 코드가 존재하는지에 대한 이유이다.
  - 프로젝트의 비즈니스 모델을 잘 알아야한다.
- 두번째
  - 모든 결정은 콘텍스트를 고려해 내려야 한다. 특정 콘텍스트에서 결정한 좋은 선택이 다른 콘텍스트에서는 나쁜 선택이 될 수도 있다.
	- 비 기능적 요구사항(NFR)을 작성하고 사용하기
	  - ex) 익명의 사용자로 로그인 해 프리미엄 영역에 접근하고 싶다. ->(NFR) 익명의 사용자로 로그인해 1초 이내에 프리미엄 영역에 접근하고 싶다.
		- 두개의 소프트웨어에서 기능적 요구사항은 동일하지만 NFR이 다르다면 다른 기술이 필요할 수 있다.
    ```
    **예시 1: 사진 앨범**
    
    - 기능적 요구사항: 사진 저장, 보기, 정렬
    
    시스템 A (개인용 포토 앨범):
    
    - NFR: 간단한 UI, 저사양 기기에서도 동작
    - 필요 기술:
        - 기본 이미지 압축
        - 로컬 파일 시스템
        - 가벼운 UI 프레임워크
    
    시스템 B (전문 사진작가용 포토 앨범):
    
    - NFR: 고화질 지원, 빠른 검색, 대용량 저장
    - 필요 기술:
        - 고급 이미지 처리
        - 클라우드 스토리지
        - 이미지 검색 엔진
    ```		
- 세번째
  - 프레임워크의 선택은 기술적인것이며 비즈니스요구를 고려해 기술 담당자가 결정해야한다.
  - TTM(Time To Market)을 줄이는데 필요한 속도와 품질 사이에서 타협점을 찾아야한다.
- 네번째
  - 프레임워크를 선택하게 한 의사 결정 기준을 팀의 모든 구성원에게 알려야한다.
	- 결정을 내리게 된 기준을 모두 공유하자.
  - LADR/ADR : 결정을 내린 이유를 레코드 하기.
	- 제목, 콘텍스트, 결정, 상태, 결과 를 포함한 문서
 ### 도구
 ![스크린샷 2024-11-10 오후 3 10 20](https://github.com/user-attachments/assets/6fe740ec-7714-40f2-b2f8-1adcacda7759)
![스크린샷 2024-11-10 오후 3 10 46](https://github.com/user-attachments/assets/16155fee-fe9a-4741-b367-3eda926e997a)

	
## Question

저는 책의 마지막장이 궁금해서 정리하면서 봤는데요! 보면서 흥미로웠던 부분이 LADR/ADR 부분이였답니다. 이런 결정의 이유를 레코드 해 놓는다면 진짜 나중에 새로운 회사에 입사했을때 감동할 것 같아서 앞으로 선택을 할때 기록해보고 싶다는 생각을 했습니다! 혹시 여러분들중 이런 결정의 사유등을 기록한 문서를 기록해 놓는 회사가 있을까요?

## 📝 Reference

[github adr](https://github.blog/engineering/why-write-adrs/)
[ADR 예시](https://github.com/alphagov/govuk-aws/tree/main/docs/architecture/decisions)

**Comment by chhw130** [comment]
특정 기술적 의사결정을 설득한 문서가 있기는 합니다..ㅋㅋ
예전에 발표했을 때 기억하실지는 모르겠지만 주도적으로 tanstack-query나 msw를 도입할때 컨플에 문서화 했었는데요.

다만 여기서 소개하는 ADR/LADR와는 느낌이 다른게, 결정 과정의 투명성을 제공하기 보다는 설득을 위주로 하다 보니 무조건 이게 더 좋다는 걸 강조하는 관점에서 작성했던 것 같습니다...ㅋㅋㅋㅋ
그래도 작성 문서에는 `우리가 이 기술을 선택해야하는 이유, 다른 기술과의 차별점, 향후 확장성 측면, 현재 프로젝트와 잘 맞는지` 등을 주요 포커스로 작성해놓았습니다.
> 그래야 추후 합류하는 인원에게도 문서를 통해 시간 비용을 줄일 수 있기 때문.
