### ISSUE TITLE
[1장] 빠르게 바뀌는 프론트엔드, React는 어떻게 될까??

### ISSUE THREAD

**Issue by chhw130** [FE-StudyWithMe/FE-without-framework#6]
## 🧐 Question
빠르게 바뀌는 프론트엔드 react는 어떻게 될까??

프론트엔드 기술들을 시간이 지남에 따라 자주 바뀌는데, 지금 1황으로 자리잡은 React또한 자리가 대체 될 수도 있을까요?
1장에 간단히 프레임워크(기술스택)에 대한 이야기가 나와서 여러분들의 생각이 궁금했습니다!

## 📝 Reference
[아무리 좋은 게 나와도 React를 이길 수 없는 이유 + 취준생이 Vue, Svelte, Angular를 배우면 안 되는 이유](https://www.youtube.com/watch?v=WRvd29xF8dc)
[React 불만 大 발설](https://www.youtube.com/watch?v=1V6mQom0paI&t=752s)

**Comment by horang-e** [comment]
제 생각에는... 일단 작은 규모로 개발하는 회사는 특히 스타트업 등의 회사에서는 React등의 주류 라이브러리, 프레임 워크를 사용할 수 밖에 없을것 같습니다..! 일단 작은 규모라면 문제를 해결해 줄 수 있는 사람이 현저히 부족하다는거고? 그럼 그 해답을 찾을 수 있는 방법은 인터넷에 있을텐데 그렇게 되면 커뮤니티가 가장 큰 React가 선택되고 사용될 확률이 가장 크다고 생각해요!

전에 다른분들 말 들어보니까 규모가 꽤 큰 개발팀을 가지고 있고 고인물분들이 있는 회사에서는 자체적으로 개발한 프레임 워크나 라이브러리를 만들어서 사용하신다고 하시더라구요..! 그치만 모든 회사가 크진 않기 때문에 왠만하면 앞으로도 한동안은 React가 1황이지 않을까 생각합니다.

**Comment by kimfield98** [comment]
저는 React에 익숙해져서 이미 잘 쓰고 있기 때문에 '왜 바꿔야할까?'라는 관점으로 생각해봤어요. 

빠른 성능을 중요시 하는 게임개발 분야를 제외한, 
일반적인 웹 개발 시장(홈페이지, 대시보드 등)에서는 개발 속도와 유지보수성이 중요해지는 측면으로 흘러가는 것 같아서
새로운 무언가가 등장하지 않는다면, 기술스택을 바꾸려는 움직임도 둔할 것 같다는 예측을 해봤습니다!

만약 새로운 기술스택을 도입해야만 한다면,
일부 팀원만 학습하고 소수의 인원이 규칙을 정하고 나머지는 비판없이 따르는? 상황을 경계할 것 같은데 ..
충분한 고민은 하지 못했지만 이를 비롯한 여러 상황들이 다른 기술스택으로의 전환을 어렵게 만드는 것 같습니다 🤔
