### ISSUE TITLE
[1장] 양방향 바인딩에 대하여

### ISSUE THREAD

**Issue by 2min0-dev** [FE-StudyWithMe/FE-without-framework#8]
### 1. 양방향 데이터 바인딩이 대규모 애플리케이션에 적합하지 않은 이유

> 양방향 데이터 바인딩이 대규모 애플리케이션에는 적합하지 않기 때문에 시간이 지나자 많은 개발자가 앵귤러JS를 떠났다.

이 문장을 보고 그 이유가 궁금해져서 찾아보아서 아래와 같은 답을 얻을 수 있었어요.

> 데이터 변화에 따라 DOM 객체 전체를 다시 렌더링하는 작업은 성능 감소를 초래할 수 있다. 특히 대규모 애플리케이션에서는 이러한 업데이트가 비용이 많이 들 수 있다.

이걸 보면서 Vue.js의 경우 업데이트 가 된 부분만 캐치하여 재랜더링을 진행하는 것으로 알고 있는데 이 경우에도 동일하게 적용하면 문제가 없었지 않았을까? 하는 생각이 들었어요. 그래서 해당 부분에 대한 의견을 나누고 싶었습니다:)

### 2. React와 Vue.js에서의 데이터 바인딩

양방향 데이터 바인딩에 대한 글을 읽으면서 문뜩 'Vue.js의 `v-model`도 양방향 바인딩이 아니었나?' 하는 생각이 들었어요.
그래서 찾아보니 양방향 바인딩처럼 보이지만 내부 코드는 단방향 바인딩을 사용했다는 것을 알 수 있었어요.
저는 Vue.js를 사용해서 Vue.js에 관해서만 알고 있는데, 다른 프레임워크나 라이브러리에서 비슷한 것이 있는지 같이 얘기 나눠보고 싶어요:)

### 1. 양방향 데이터 바인딩이 대규모 애플리케이션에 적합하지 않은 이유
[데이터 바인딩 - 양방향 데이터와 단방향 데이터의 차이와 장단점](https://velog.io/@jiyaho/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B0%94%EC%9D%B8%EB%94%A9-%EC%96%91%EB%B0%A9%ED%96%A5-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%99%80-%EB%8B%A8%EB%B0%A9%ED%96%A5-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%99%80-%EC%9E%A5%EB%8B%A8%EC%A0%90)
[[React] 양방향 바인딩과 단방향 바인딩 간단하게 알아보기](https://oliviakim.tistory.com/91)
[[React] 양방향/단방향 바인딩, 부모 컴포넌트의 state 바꾸기](https://gitnyang.tistory.com/entry/React-%EC%96%91%EB%B0%A9%ED%96%A5-%EB%8B%A8%EB%B0%A9%ED%96%A5-%EB%B0%94%EC%9D%B8%EB%94%A9-%EB%B6%80%EB%AA%A8-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EC%9D%98-state-%EB%B0%94%EA%BE%B8%EA%B8%B0)
[(Claude 질문) 양방향 데이터 바인딩이 대규모 애플리케이션에는 적합하지 않은 이유](https://poe.com/s/0wajmKhE3JBLPVAvVuEF)

### 2. React와 Vue.js에서의 데이터 바인딩
[Vue.js Component v-model](https://ko.vuejs.org/guide/components/v-model)
[(Claude 질문) vue의 v-model](https://poe.com/s/5gJc2U1ARXMagKpLAnz3)

**Comment by kimfield98** [comment]
```js
function Form() {
  const [name, setName] = useState('');

  return (
    <input
      value={name}
      onChange={e => setName(e.target.value)}
    />
  );
}
```


React에서 양방향 바인딩과 유사하게 구현하기 (폼 요소에서는 controlled component 패턴을 사용)

- 상태에서 뷰로의 데이터 흐름: value={formData.fieldName}
- 뷰에서 상태로의 데이터 흐름: onChange={handleChange}

이 패턴은 양방향 바인딩처럼 보이지만, 실제로는 단방향 데이터 흐름을 사용합니다. 
상태(name)는 컴포넌트에서 관리되며, 입력 값이 변경될 때마다 onChange 이벤트 핸들러를 통해 상태를 업데이트합니다. (명시적)

진정한 양방향 바인딩에서는 뷰의 변경이 자동으로 모델(상태)을 업데이트하고, 그 반대도 마찬가지입니다.
React의 이 패턴에서는 상태에서 뷰로의 업데이트는 자동이지만, 뷰에서 상태로의 업데이트는 명시적인 함수 호출을 통해 이루어집니다.

---
저는 단방향 데이터 바인딩으로 구현된 리액트를 주로 사용하기 때문에,
비슷하게 양방향 바인딩처럼 보일 수 있는 구현 방법을 찾아보았습니다!

vue나 다른 스택을 쓰시는 분들의 이야기도 궁금하네요 👀

**Comment by chhw130** [comment]
양방향 바인딩도 결국 단방향으로 아래 처럼 추상화되어 있습니다.

![image](https://github.com/user-attachments/assets/6c767caf-b00d-424a-8eaa-eec291140ea2)

단방향 바인딩이 개인적으로 흐름을 따라가기 쉽다고 느껴졌습니다.(애플리케이션이 복잡해질 수록)
